### ISSUE TITLE
Document how to build the project in the README file

### ISSUE THREAD

**Issue by omefire** [input-output-hk/cardano-sl#1700]
It'd be great if the README file described a way to build the project and get it running.

**Comment by denisshevchenko** [comment]
Check this out, please: https://cardanodocs.com/for-contributors/building-from-source/

**Comment by omefire** [comment]
Thanks, @denisshevchenko. Currently building.

**Comment by omefire** [comment]
I also found this link, that might be useful: 
```https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-core-from-scratch.md```

**Comment by buzztiaan** [comment]
Would be nice if that last document would tell what nixos is because atm i'm sitting here downloading mountains of untrusted binaries from them to build your software.

**Comment by buzztiaan** [comment]
Or, describe how to build it without nixos

**Comment by denisshevchenko** [comment]
> Would be nice if that last document would tell what nixos

@buzztiaan You don't need NixOS, just Nix. Nix is a package manager, and NixOS is a Linux distro based on this package manager.

And you're right, it's possible to build Cardano SL without Nix, but this method isn't recommended.

> i'm sitting here downloading mountains of untrusted binaries from them

All these "untrusted binaries" are stored in `/nix/store`, it's completely safe for your system. Anyway, you can always uninstall Nix and remove `/nix/store` directory.

**Comment by denisshevchenko** [comment]
https://cardanodocs.com/for-contributors/building-from-source/#build-commands
https://cardanodocs.com/for-contributors/building-from-source/#build-commands-without-nix

@buzztiaan @omefire ^

**Comment by buzztiaan** [comment]
the command 'stack' is part of nix , are you sure?

**Comment by jc423** [comment]
Hey been trying to build from source on Windows 10 without nix and keep running into issue.  Not sure if you have any guidance.  You can see I'm using extra-include-dirs

    Preprocessing library concurrent-extra-0.7.0.10...
    realgcc.exe: fatal error: no input files
    compilation terminated.
    `gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)

**Comment by denisshevchenko** [comment]
> the command 'stack' is part of nix , are you sure?

No, `stack` is not a part of Nix. It's a separate Haskell tool.

> Hey been trying to build from source on Windows 10 without nix and keep running into issue. 

@jc423 Sorry, I don't use Windows since 2008... BTW, why do you use raw `stack build` command? We have a special script for building: `./scripts/build/cardano-sl.sh`.

**Comment by jc423** [comment]
@denisshevchenko the raw stack build was what I saw in was run from output from build script.  I'll keep trying maybe just dual boot.  There was another closed issue I saw previously regarding openssl32.  Do you happen to know which binary should be downloaded?  I used the openssl installer and I think that may not install the correct version.

**Comment by jc423** [comment]
I think I need to be using v1.0.x not 1.1.x.  And the issue above on gcc.exe may be related to long paths in Windows.  I'll update when I confirm this.

**Comment by domenkozar** [comment]
Yes, we have hacks in the CI to make stack paths with short prefix so everything can fit within the limits.

**Comment by domenkozar** [comment]
Docs are now in https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md please reopen if you have more issues.

**Comment by slotfi64** [comment]
this is broken link (404)!
 https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

**Comment by SebastienGllmt** [comment]
@slotfi64 try looking at the develop branch
https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

**Comment by slotfi64** [comment]
I see! I managed to add libeay32.dll but still adding libssl32.dll wont make the error go away! 
is there any haskell package i need to get that includes ssl32? since including the dll manually is not being recognized.

**Comment by highdev2016** [comment]
How can I build the cardano-sl in windows?

**Comment by highdev2016** [comment]
Hello, guys.

I've installed OpenSSL-Win32 on my pc (Windows 10) and executed cardaon-sl.sh but it makes that error all the time.


    Building cardano-sl-crypto
    
    stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=4 
    --extra-include-dirs=C:/OpenSSL-Win32/include/ --extra-lib-dirs=C:/OpenSSL-Win32/lib 
    --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-crypto
    
    Warning: There were multiple candidates for the Cabal entry " hlint.hs
         * D:\bitcoin\cardano-sl\.stack-work\downloaded\XTTklt4ROs4T\hlint.hs
         picking: D:\bitcoin\cardano-sl\.stack-work\downloaded\XTTklt4ROs4T\tests\hlint.hs
    cryptonite-openssl-0.6: configure

    --  While building custom Setup.hs for package cryptonite-openssl-0.6 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe 
    --builddir=.stack-work\dist\ca59d0ab configure --with-ghc=C:\Users\Chen\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE 
    --with-ghc-pkg=C:\Users\Chen\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE 
    --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\6dde1a60\pkgdb 
    --libdir=C:\sr\snapshots\6dde1a60\lib --bindir=C:\sr\snapshots\6dde1a60\bin 
    --datadir=C:\sr\snapshots\6dde1a60\share --libexecdir=C:\sr\snapshots\6dde1a60\libexec --sysconfdir=C:\sr\snapshots\6dde1a60\etc 
    --docdir=C:\sr\snapshots\6dde1a60\doc\cryptonite-openssl-0.6 
    --htmldir=C:\sr\snapshots\6dde1a60\doc\cryptonite-openssl-0.6 
    --haddockdir=C:\sr\snapshots\6dde1a60\doc\cryptonite-openssl-0.6 
    --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1 --dependency=cryptonite=cryptonite-0.23-5py7i5OSd6E8YiifK94740 --dependency=memory=memory-0.14.6-8jCU2t7lCy47HL9wtlgonQ --ghc-options " -Wwarn" --extra-include-dirs=C:/OpenSSL-Win32/include/ 
    --extra-include-dirs=C:\Users\Chen\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include 
    --extra-lib-dirs=C:/OpenSSL-Win32/lib --extra-lib-dirs=C:\Users\Chen\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin 
    --extra-lib-dirs=C:\Users\Chen\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
    Process exited with code: ExitFailure 1
    Logs have been written to: D:\bitcoin\cardano-sl\.stack-work\logs\cryptonite-openssl-0.6.log

    Configuring cryptonite-openssl-0.6...
    Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.2.exe: Missing dependencies on foreign
    libraries:
    * Missing C libraries: eay32, ssl32
    This problem can usually be solved by installing the system packages that
    provide these libraries (you may need the "-dev" versions). If the libraries
    are already installed but in a non-standard location then you can use the
    flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.

How can I fix it?
Thank you.
