### ISSUE TITLE
Stack setup failed with link error within nix shell

### ISSUE THREAD

**Issue by frasermince** [input-output-hk/cardano-sl#1759]
I am trying to build from source in nix-shell but on stack setup I get this error: https://github.com/NixOS/nixpkgs/issues/25139. There seems to be an existing patch. But I do not know enough about Nix to know how to apply that patch. I see this on both master and cardano-sl-1.0.

**Comment by frasermince** [comment]
I fixed it! I was using https://cardanodocs.com/for-contributors/building-from-source/ as a tutorial instead of https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-core-from-scratch.md. Using the latter one made it work. You might want to consider making these the same.

**Comment by domenkozar** [comment]
cc @denisshevchenko

**Comment by domenkozar** [comment]
We have now united the two documents under https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
