### ISSUE TITLE
cryptonite-openssl-0.6: configure

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#1947]
Configuring cryptonite-openssl-0.6...
Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependency on a foreign
library:
* Missing C library: crypto
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.

**Comment by tanzeelrana** [comment]
https://www.ianweatherhogg.com/tech/2015-12-05-crypto-ssl-error-debian-hsopenssl-install.html

**Comment by domenkozar** [comment]
Same as https://github.com/input-output-hk/cardano-sl/issues/1948

**Comment by afzydev** [comment]
@domenkozar 
I am facing an issue when installing on my Ubuntu system.

> Configuring cryptonite-openssl-0.6...
>     Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: Missing dependency on a foreign
>     library:
>     * Missing C library: crypto
>     This problem can usually be solved by installing the system package that
>     provides this library (you may need the "-dev" version). If the library is
>     already installed but in a non-standard location then you can use the flags
>     --extra-include-dirs= and --extra-lib-dirs= to specify where it is.

I have already installed 

> sudo apt-get install libssl-dev

 still not able to resolve this issue.

Thanks

**Comment by erikd** [comment]
@afzydev Which version of Ubuntu? What's the output of the command:
```
dpkg -l | grep libssl
```

**Comment by afzydev** [comment]
Here is the output

> 
> ii  libssl-dev:amd64                                      1.1.0g-2.1+ubuntu14.04.1+deb.sury.org+1                  amd64        Secure Sockets Layer toolkit - development files
> ii  libssl1.0.0:amd64                                     1.0.1f-1ubuntu2.22                                       amd64        Secure Sockets Layer toolkit - shared libraries
> ii  libssl1.1:amd64                                       1.1.0g-2.1+ubuntu14.04.1+deb.sury.org+1                  amd64        Secure Sockets Layer toolkit - shared libraries
>

**Comment by erikd** [comment]
I suspect Ubuntu 14.04 is too old. There were a lot of OpenSSL changes after the Heartbleed bug which happened around 2 years ago.

I'm pretty sure this would work on Ubuntu 16.04.

**Comment by afzydev** [comment]
@erikd 
Thanks for your commendable support.
