### ISSUE TITLE
ERROR: Preprocessing library cardano-sl-db-1.0.3... 

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#1948]
[89 of 92] Pos.Aeson.Crypto
[90 of 92] Pos.Aeson.Core
[91 of 92] Pos.Aeson.Genesis
[92 of 92] Pos.Aeson.Core.Configuration
cardano-sl-core-1.0.3: copy/register
Installing library in
/home/tanzeel/cardano-sl/.stack-work/install/x86_64-linux/lts-9.1/8.0.2/lib/x86_64-linux-ghc-8.0.2/cardano-sl-core-1.0.3-53BeS6I7xex1jKrwJA5uqs
Registering cardano-sl-core-1.0.3...
Building cardano-sl-db

stack build --ghc-options="-DGITREV=8bf4b3c8072d8c8fcc1df2794c7da991cd0fb258 -Wwarn +RTS -A256m -n2m -RTS" --test --no-haddock-deps --bench --jobs=4 --flag cardano-sl:with-wallet --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-db

rocksdb-haskell-1.0.0: download
rocksdb-haskell-1.0.0: configure
rocksdb-haskell-1.0.0: build
rocksdb-haskell-1.0.0: copy/register
stack build --ghc-options="-DGITREV=8bf4b3c8072d8c8fcc1df2794c7da991cd0fb258 -Wwarn +RTS -A256m -n2m -RTS" --test --no-haddock-deps --bench --jobs=4 --flag cardano-sl:with-wallet --no-run-tests --no-run-benchmarks --fast  cardano-sl-db

cardano-sl-db-1.0.3: configure (lib)
Configuring cardano-sl-db-1.0.3...
cardano-sl-db-1.0.3: build (lib)
Preprocessing library cardano-sl-db-1.0.3...
[ 1 of 13] Pos.DB.Error
[ 2 of 13] Pos.DB.Class
[ 3 of 13] Pos.DB.Functions
[ 4 of 13] Pos.DB.Misc.Common
[ 5 of 13] Pos.DB.Pure

--  While building package cardano-sl-db-1.0.3 using:
      /home/tanzeel/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:cardano-sl-db --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure (-4)

**Comment by tanzeelrana** [comment]
tanzeel@tanzeel01:~/cardano-sl$ which ghc
tanzeel@tanzeel01:~/cardano-sl$ 
tanzeel@tanzeel01:~/cardano-sl$ ghc --version
The program 'ghc' is currently not installed. You can install it by typing:
sudo apt install ghc
tanzeel@tanzeel01:~/cardano-sl$ sudo apt install ghc

https://github.com/commercialhaskell/stack/issues/721

**Comment by domenkozar** [comment]
Please always use `--nix` when calling stack. Otherwise you're on your own, installing system dependencies.
