### ISSUE TITLE
MissingSystemStartTime

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/cardano-sl#2073]
I have build cardano-node-simple as per instruction in een Docker Ubuntu and when executing I get the following error: 
[Attention] We are in PRODUCTION mode
cardano-node-simple: MissingSystemStartTime

Any suggestions on how to continue?

**Comment by zmeel** [comment]
Never mind. It is a Docker Ubuntu problem.

**Comment by zmeel** [comment]
I have to reopen this. 
This time I setup a full functional virtual machine with Ubuntu server and installed cardano-node-simple as per instruction. Again when running _cardano-node-simple_ I get the following error:

[Attention] We are in PRODUCTION mode
cardano-node-simple: MissingSystemStartTime

Any help would be appreciated.

**Comment by zmeel** [comment]
Oke, never mind. This is the error if you start the node by simply use _cardano-node-simple_ as command without any parameters.

**Comment by ocharles** [comment]
@zmeel so what are you meant to start the node with?

**Comment by zmeel** [comment]
@ocharles That was 2 weeks ago. I just tried to executed _cardano-node-simple_ which didn't work out (of course). Now I start the cardano-sl with wallet through the connect-to-mainnet script.

**Comment by GlenKPeterson** [comment]
Hi, if anyone else is blindly following the instructions [here](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) as though you've never used nix-build before, I think you want to build the wallet separately.  There's a whole bunch of artifacts listed at the aforementioned page.  Just use the one you want as the argument to -A, so to build the wallet:

```sh
nix-build -A cardano-sl-wallet --cores 0 --max-jobs 2 --no-build-output --out-link master
```
Then:
```sh
$ ls master/bin
cardano-node  cardano-swagger  cardano-wallet-hs2purs
```
Now I think you're supposed to do something like this:
```sh
[nix-shell:~/cardano-sl]$ cd
[nix-shell:~]$ git clone https://github.com/input-output-hk/daedalus.git
[nix-shell:~]$ cd daedalus
[nix-shell:~/daedalus]$ npm install
```
I did that in my host OS (not in nix-shell) so not sure what's going to come of that.  It's late, I have no idea what I'm doing.  Looks like everything completed OK, but now what?

**Comment by samhattangady** [comment]
Hey, so I was facing the same problems.

Basically, once you're done building from source, you have to move on to the next stage, https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/connect-to-cluster.md

Once you've followed the steps listed, you will find a script called `connect-to-mainnet` in your `cardano-sl` folder. Run this script. I believe this starts the daemon.

Then go to that daedalus folder, and run `npm run start` to launch the wallet.
