### ISSUE TITLE
Error building cardano-sl-tools-static

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/cardano-sl#2077]
I have successfully build _cardano-sl-static_,  _cardano-sl-wallet_ and _cardano-report-server-stat_ic but when trying to build cardano-sl-tools-static (nix-build -A cardano-report-server-static --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0) I get the following error:
error: attribute ‘cardano-sl-tools-static’ in selection path ‘cardano-sl-tools-static’ not found

Any help is welcome.

**Comment by akegalj** [comment]
@zmeel can you link what install instructions have you followed?

**Comment by zmeel** [comment]
Hi akegalj,

I have installed according to the [Nix build mode (recommended)](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md#nix-build-mode-recommended) with the exception that I had to add build-users-group = to /etc/nix/nix.conf.

I have build all Cardano components except the cardano-sl-tools-static.

Best,
Erik

**Comment by akegalj** [comment]
@zmeel Strange. 

I can confirm it is like that. Unfortunately I don't have much experience with `nix` so I will ask @jmitchell and @deepfire if they can have a look what is wrong here.

I have tried experimenting and I can confirm building `cardano-sl-tools-static` with nix fails:
```
[akegalj@notebook cardano-sl]$ nix-build -A cardano-sl-tools-static --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0
error: attribute ‘cardano-sl-tools-static’ in selection path ‘cardano-sl-tools-static’ not found
```
but removing `-static` will make a progress:
```
[akegalj@notebook cardano-sl]$ nix-build -A cardano-sl-tools --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0
warning: dumping very large path (> 256 MiB); this may run out of memory
...
...
```

and it will probably build it (build still in progress atm of writing this). I am not sure what is difference with `-static` and without it.

@jmitchell @deepfire @domenkozar could it be it is just a typo in our build instructions and it should be without `-static`?

@zmeel please try what I have proposed above - it will probably solve your problems.

**Comment by zmeel** [comment]
Hi Ante,
I'm building currently as you proposed. I will report back...
Erik

**Comment by zmeel** [comment]
Build is successful!

**Comment by akegalj** [comment]
Nice :) Closing the issue.

**Comment by pip010** [comment]
there are still wrong instructions here (this is pointed from the official site :https://cardanodocs.com/installation/)  https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

**Comment by 4x4V8** [comment]
This shows as fixed but as of now the document shows:

> Actually building the Cardano SL node (or, most likely, simply obtaining it from the IOHK's binary caches) can be performed by building the attribute cardano-sl-static:
> 
> $ nix-build -A cardano-sl-static --cores 0 --max-jobs 2 --no-build-output --out-link master

Can you remove "-static" from the lines above?

**Comment by Sotatek-CongNguyen** [comment]
3/1/2019, I still meet this error
```
error: attribute 'cardano-sl-node-static' in selection path 'cardano-sl-node-static' not found
```
