### ISSUE TITLE
Error launching cardano-node

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/cardano-sl#2078]
I have build all packages according to [Nix build mode (recommended)](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md#nix-build-mode-recommended).
I then moved all packages to ./cardano-sl/.stack-work/install/x86_64-linux-nix/lts-9.1/8.0.2/bin/
I then launched cardano-node with **stack exec -- cardano-launcher** and get the following error:

_Invalid option `--extra-lib-dirs=/nix/store/i8wz3m067dzbs5x2glhxvcg7lvds1942-zlib-1.2.11/lib'_

/nix/store/i8wz3m067dzbs5x2glhxvcg7lvds1942-zlib-1.2.11/lib is present.

Running **stack exec -- cardano-launcher** with all options given by **cardano-launcher --help** results in the same error.

Am I doing something wrong? What is the correct way of starting cardano-sl?
I would very much appreciate some help.

Thanks,
Erik

**Comment by zmeel** [comment]
Oke, I have build the connect-to-cluster and executed with **stack exec -- ./connect-to-mainnet**
That seems to work! The node is up but running in a terminal giving lot's of output. I cannot close the terminal session this way. How to run it as a daemon? With nohup?

**Comment by zmeel** [comment]
I'm running this now by executing: **nohup stack exec -- ./connect-to-mainnet >/dev/null 2>&1 &**

It is running now in the background and I can close the console without interrupting the node. I guess this is OK to do. If not please comment. 
Closing the issue for now.

**Comment by sneha6patel** [comment]
Hello @zmeel  I've tried your command **nohup stack exec -- ./connect-to-mainnet >/dev/null 2>&1 &** and it run until I shut down the PC..When I just come back and run my code the script is not running in the background automatically.Please help me with permanent solution.
