### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by LukSroczynski** [input-output-hk/cardano-sl#2106]
I had my wallet with 700 ADA. I wanted to recover another wallet and application froze at "connecting to Network". I tried to restart computer but nothing seems to work...

**Comment by cleverca22** [comment]
that is a known bug, the wallet restore stops it from connecting, just leave it running for about an hour

**Comment by LukSroczynski** [comment]
True. You have to wait or restart app few times and eventually it started to work again :) 
Thanks
