### ISSUE TITLE
How to get this thing working?

### ISSUE THREAD

**Issue by h4ck3rm1k3** [input-output-hk/cardano-sl#2112]
followed instructions : How to connect to cluster
I have gotten it connected I think, but am lacking a gui.
is this working or not?
```
[node.server.block:DEBUG:ThreadId 159506] [2017-12-13 18:06:15 EST] Header 763d5efc potentially represents good alternative chain, will process
[node.server.block:DEBUG:ThreadId 159506] [2017-12-13 18:06:15 EST] addToBlockRequestQueue, : MainBlockHeader:
    hash: 763d5efc2e40bca0403e78ad61a5bae017c16b591a0a31509385caa5dce514d4
    previous block: 162b8dbb2f2c521fed6cb455c256ec227f73a73797c08b208f6e0b66729319c6
    slot: 4564th slot of 16th epoch
    difficulty: 350117
    leader: pub:1bc97a2f
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = epoch #0, iPk = pub:1bc97a2f, dPk = pub:61261a95 } }
    block: v0.1.0
    software: cardano-sl:0

[node.server.block:WARNING:ThreadId 159506] [2017-12-13 18:06:15 EST] Failed to add headers from "52.196.48.204:3000:0" to block retrieval queue: queue is full
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:15 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:19 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:23 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:27 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:31 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:35 EST] recoveryCommGuard: recovery in process, skipping action
[node.server.block:DEBUG:ThreadId 159510] [2017-12-13 18:06:35 EST] handleBlockHeaders: got some unsolicited block header(s)
[node.server.block:DEBUG:ThreadId 159510] [2017-12-13 18:06:36 EST] handleUnsolicitedHeader: single header 0dfd6e92 was propagated, processing
[node.server.block:DEBUG:ThreadId 159510] [2017-12-13 18:06:36 EST] Header 0dfd6e92 potentially represents good alternative chain, will process
[node.server.block:DEBUG:ThreadId 159510] [2017-12-13 18:06:36 EST] addToBlockRequestQueue, : MainBlockHeader:
    hash: 0dfd6e92d6eaba315ec8d00c1b55a9b80718c8b1339531c764a5e939bf7d8ef8
    previous block: 763d5efc2e40bca0403e78ad61a5bae017c16b591a0a31509385caa5dce514d4
    slot: 4565th slot of 16th epoch
    difficulty: 350118
    leader: pub:9a6fa343
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = epoch #0, iPk = pub:9a6fa343, dPk = pub:8b532076 } }
    block: v0.1.0
    software: cardano-sl:0

[node.server.block:WARNING:ThreadId 159510] [2017-12-13 18:06:36 EST] Failed to add headers from "52.196.48.204:3000:0" to block retrieval queue: queue is full
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:39 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:43 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:47 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:51 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:55 EST] recoveryCommGuard: recovery in process, skipping action
[node.server.block:DEBUG:ThreadId 159514] [2017-12-13 18:06:57 EST] handleBlockHeaders: got some unsolicited block header(s)
[node.server.block:DEBUG:ThreadId 159514] [2017-12-13 18:06:57 EST] handleUnsolicitedHeader: single header 320aaf37 was propagated, processing
[node.server.block:DEBUG:ThreadId 159514] [2017-12-13 18:06:57 EST] Header 320aaf37 potentially represents good alternative chain, will process
[node.server.block:DEBUG:ThreadId 159514] [2017-12-13 18:06:57 EST] addToBlockRequestQueue, : MainBlockHeader:
    hash: 320aaf373717927d6172f154d88e6378f573dfd625d8279d7f7f5a6c6114b03b
    previous block: 0dfd6e92d6eaba315ec8d00c1b55a9b80718c8b1339531c764a5e939bf7d8ef8
    slot: 4566th slot of 16th epoch
    difficulty: 350119
    leader: pub:993a8f05
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = epoch #0, iPk = pub:993a8f05, dPk = pub:89c29f8c } }
    block: v0.1.0
    software: cardano-sl:0

[node.server.block:WARNING:ThreadId 159514] [2017-12-13 18:06:57 EST] Failed to add headers from "52.196.48.204:3000:0" to block retrieval queue: queue is full
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:06:59 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:07:03 EST] recoveryCommGuard: recovery in process, skipping action
[node.worker.security:DEBUG:ThreadId 2548] [2017-12-13 18:07:07 EST] recoveryCommGuard: recovery in process, skipping action

```

**Comment by akegalj** [comment]
I believe this is alright. Right @gromakovsky ?

After it you should setup daedalus UI https://github.com/input-output-hk/daedalus

**Comment by gromakovsky** [comment]
Yes, node itself (backend) works fine (judging by these logs).

**Comment by h4ck3rm1k3** [comment]
Thank you, I will attempt to build the front end again.

**Comment by zmeel** [comment]
@h4ck3rm1k3 
I would love to hear if you succeeded in building the front end and get it to work. 

I have already tried for many days. I have a front end but cannot connect to it. I suppose I have to connect to http://localhost:4000 but I'm not sure. I have tried to link the daedalus-client-api but get the error 'daedalus-client-api' is not in the npm registry. I guess that is related to [2057](https://github.com/input-output-hk/cardano-sl/issues/2057). I'm not even sure if it is possible to build the front end at the moment. I have the back end running.

**Comment by h4ck3rm1k3** [comment]
I have gotten it built clean now following the instructions.
I will try and connect, what instructions are you following for running the front end as a webserver?

**Comment by h4ck3rm1k3** [comment]
I have an update, first the hot needs to be run inside of xwindows, it starts the chromium browser. Start them separately.

**Comment by h4ck3rm1k3** [comment]
Here are my build instructions https://github.com/h4ck3rm1k3/daedalus/blob/master/README.md @zmeel

**Comment by zmeel** [comment]
I'm trying to run the node and wallet in a Ubuntu docker on my Synology DS415+ so I can run the node 24/7. I can run the node in the container but cannot connect the wallet to it. Apparently, the wallet needs Xwindows. I just read your instructions and going to try these out. Thanks!

**Comment by h4ck3rm1k3** [comment]
yes you need a gui
so use port forwarding to send the ports to you display

**Comment by h4ck3rm1k3** [comment]
https://utopian.io/utopian-io/@h4ck3rm1k3st33m/building-on-debian-gnu-linux give me a vote here please

**Comment by zmeel** [comment]
I see you run the daedalus front end on your labtop. Which OS is on the laptop?

**Comment by h4ck3rm1k3** [comment]
debian of course....

**Comment by h4ck3rm1k3** [comment]
Linux mdupont-Aspire-7750G 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux
debian/sid

**Comment by h4ck3rm1k3** [comment]
but the front end is pure javascript/electron so should work anywhere. I am going to see if next I can get rid of the port forwarding.

**Comment by zmeel** [comment]
Oke, thanks. I'm going to try to get it running on my MacBook Pro. I'm really appreciate your work on this.

**Comment by h4ck3rm1k3** [comment]
so if you appreciate it, here is my cardano addr, DdzFFzCqrht1pcFJCrF6aXSrEkLuGT1GXCsf7HjMGcsvE3fQiY7voGPYtxyWfKEC3zq5PtqC7ABuAgztD8R7aFvJVtG1PueqtnEBmhYt you can send me a bit. Or upvote my post on utopian.io here https://utopian.io/utopian-io/@h4ck3rm1k3st33m/building-on-debian-gnu-linux

**Comment by 5chdn** [comment]
> followed instructions : How to connect to cluster

Sorry, I'm trying to figure out this for two weeks now. Can you share the link to this piece of information. I have cardano-sl node and daedalus node wallet installed from source, but I can not figure out how to connect to the main network. Thanks!

**Comment by 5chdn** [comment]
@h4ck3rm1k3 ?

> Start the backend :
>
>     ./connect-to-mainnet

Where do you find that script? It's not mentioned anywhere and I do not have this after building _all_ cardano-* components with nixos.

    [nix-shell:~/.opt/cardano-sl]$ find . | grep -i connect\-to\-mainnet
        (...)

:-/

**Comment by 5chdn** [comment]
Okay, wow, this was very well hidden :)

https://github.com/input-output-hk/cardano-sl/blob/cardano-sl-1.0/docs/how-to/connect-to-cluster.md

**Comment by h4ck3rm1k3** [comment]
Yes, the docs are crap.

**Comment by 5chdn** [comment]
> Syncing blocks 2.40%

This took me only 2 weeks to figure out lol

**Comment by h4ck3rm1k3** [comment]
https://utopian.io/utopian-io/@h4ck3rm1k3st33m/at-100-now-what i am at 100% but now what?

**Comment by 5chdn** [comment]
Can't read this without creating an account. How long did it take you to get to 100%?

**Comment by h4ck3rm1k3** [comment]
what? 
here is the text :+1: ```
dupont@mdupont-Aspire-7750G:~/experiments/daedalus$ npm run start-hot

> daedalus@0.8.0 start-hot /home/mdupont/experiments/daedalus
> cross-env HOT=1 NODE_ENV=development electron -r babel-register -r babel-polyfill ./electron/main.development
```
Gives me now :
![image](https://res.cloudinary.com/hpiynhbhq/image/upload/v1513545246/c1fsgvrxjtriirjg0959.png)

Backend node is showing :
```
[node.worker.security:DEBUG:ThreadId 554] [2017-12-17 16:15:10 EST] recoveryCommGuard: recovery in process, skipping act\
ion
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] requestHeaders: inRecovery = True
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] requestHeaders: received 1 headers of total size 653 B from nodeI\
d "52.196.48.204:3000:0": [bcd193f4]
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] Classifying headers: [bcd193f4]
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] Received valid headers, can request blocks from bcd193f4 to bcd19\
3f4
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] self: inFlight = fromList []
[node:DEBUG:ThreadId 169945] [2017-12-17 16:15:10 EST] self: message MsgRequestBlocks (fromList [NodeId 52.196.48.204:30\
00:0]) enqueued to [NodeId 52.196.48.204:3000:0]
[node:DEBUG:ThreadId 170048] [2017-12-17 16:15:10 EST] self: sending MsgRequestBlocks (fromList [NodeId 52.196.48.204:30\
00:0]) to NodeId 52.196.48.204:3000:0
[node.wallet.servant:INFO:ThreadId 170053] [2017-12-17 16:15:11 EST] 
GET
    :> api
    :> settings
    :> sync
    :> progress
   Status: OK 0.00040846s > progress=367058/367059 peers=0
[node.wallet.servant:INFO:ThreadId 170057] [2017-12-17 16:15:12 EST] 
```

I need a better error message if there is one please

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@h4ck3rm1k3st33m/at-100-now-what">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

Took me a few hours I guess?

**Comment by h4ck3rm1k3** [comment]
https://steemit.com/utopian-io/@h4ck3rm1k3st33m/at-100-now-what

**Comment by 5chdn** [comment]
Can you click the A? Or the Cardano logo? Or the _daedalus_?

**Comment by 5chdn** [comment]
I managed to get in now.

> so if you appreciate it, here is my cardano addr,  DdzFFzCqrht1pcFJCrF6aXSrEkLuGT1GXCsf7HjMGcsvE3fQiY7voGPYtxyWfKEC3zq5PtqC7ABuAgztD8R7aFvJVtG1PueqtnEBmhYt you can send me a bit. 

Sent you a bit to test ;)

**Comment by h4ck3rm1k3** [comment]
@5chdn thank you very much.
https://github.com/h4ck3rm1k3/cardano-sl I have gotten the latest version of the node running with the latest version of the front end, my problem was the gui was newer than the latest version and the time check api was not implemented in the server.

**Comment by 5chdn** [comment]
Thanks for sharing !
