### ISSUE TITLE
Documentation outdated about cardano-wallet

### ISSUE THREAD

**Issue by jluttine** [input-output-hk/cardano-sl#2140]
Hi! According to docs, there should a CLI wallet executable called `cardano-wallet`: https://cardanodocs.com/technical/cli-options/#cardano-wallet

I haven't found any instructions on how to compile it or where to find it. Where can I find it?

In the build instructions https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md#nix-build-mode-recommended only `cardano-wallet-hs2purs` executable is mentioned.

**Comment by jluttine** [comment]
Also, the docs state: "Please notice that wallet web API is available only if you run a node with --wallet option." in https://cardanodocs.com/technical/wallet-backend/#wallet-backend-api

However, I tried running both `cardano-node` and `cardano-node-simple` with `--wallet` flag but both raised an error that it's an invalid option. So what is the node executable I should pass `--wallet` flag to?

**Comment by fschr** [comment]
I second this issue.

One of three things must be the case:

1. `cardano-wallet` used to be, but is no longer included in Cardano SL.
2. `cardano-wallet` is not yet a part of any stable branch.
3. `cardano-wallet` is included in the `cardano-sl-1.0` branch, but neither of us see how to build it.

**Comment by gromakovsky** [comment]
`cardano-wallet` was renamed to `cardano-node`.
`--wallet` flag was removed.
Those docs are very outdated 😔

**Comment by fschr** [comment]
@gromakovsky Thank you! In a couple days, I will build cardano-wallet. If the docs aren't updated by that time, I'll submit a PR.

**Comment by morenoh149** [comment]
reviewing https://cardanodocs.com/technical/cli-options/ and https://github.com/input-output-hk/cardanodocs.com/commits/master/_docs/technical/2017-01-01-cli-options.md looks like references to `cardano-wallet` have been removed. This issue should be closed.

**Comment by niespodd** [comment]
@morenoh149 The documentation still refers to the outdated "--wallet" flag in [the CARDANO SL WALLET BACKEND section](https://cardanodocs.com/technical/wallet-backend/#wallet-backend-api ).
