### ISSUE TITLE
error: getting status of ‘/home/devel/default.nix’: No such file or directory

### ISSUE THREAD

**Issue by julian1** [input-output-hk/cardano-sl#2147]
First time, following instructions, https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md

```

devel@debian:~$ ls /nix/
store  var

devel@debian:~$ cat /etc/nix/nix.conf 
binary-caches             = https://cache.nixos.org https://hydra.iohk.io
binary-caches-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=

devel@debian:~$ echo $NIX_PATH
nixpkgs=/home/devel/.nix-defexpr/channels/nixpkgs

devel@debian:~$ nix-build -A cardano-sl-static --cores 0 --max-jobs 2 --no-build-output --out-link cardano-sl-1.0
error: getting status of ‘/home/devel/default.nix’: No such file or directory

devel@debian:~$ 
```

Linux debian 4.9.0-4-amd64 #1 SMP Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux

**Comment by jptcnde** [comment]
how did you resolved this issue? I'm experiencing this too

**Comment by julian1** [comment]
@jptcnde You need to checkout the repo and then cd into it before running the nix-build. I managed to get the binaries built, but didn't manage to make any progress on how to actually launch/run a node.

**Comment by rreimche** [comment]
And now I'm getting 

`error: while setting up the build environment: getting attributes of path '': No such file or directory
(use '--show-trace' to show detailed location information)`

on nix-build -A scripts.ff.node -o ff-node-local inside cardano-node directory.
