### ISSUE TITLE
binary-caches-public-keys is possible a typo (How to Build Cardano SL from Source Code Instruction)

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/cardano-sl#2177]
looks like `binary-caches-public-keys` is a typo in [build-cardano-sl-and-daedalus-from-source-code.md line 54](../blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md#54). 

[nix-daemon.nix](https://github.com/NixOS/nixpkgs/blob/6b3b7085010a4d959b35204919a8d1228f26651f/nixos/modules/services/misc/nix-daemon.nix#L48) provides `binary-cache-public-keys`

**Comment by domenkozar** [comment]
Thanks, fixed in https://github.com/input-output-hk/cardano-sl/commit/520ee7951ce508b38341aebf017ab21e4a06dc21
