### ISSUE TITLE
getLocalTimeDifference API not present in master branch

### ISSUE THREAD

**Issue by zmeel** [input-output-hk/cardano-sl#2184]
It seems that the getLocalTimeDifference API is not present in the master branch of Cardano-sl.
I have been building two different versions of Cardano-SL ([official](https://github.com/input-output-hk/cardano-sl)) and ([fork](https://github.com/h4ck3rm1k3/cardano-sl)). 

With the official build Daedalus wallet always stuck at 100.00% syncing while with the fork the wallet runs nice and has been restored. The difference between the two builds it the _getLocalTimeDifference_ API

Running the API on the official build:
<pre>
root@43e7e58b48fa:/etc/ssl/certs# curl --cacert ca.crt -v https://localhost:8090/api/settings/time/difference
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8090 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: DC=io; DC=iohk; O=Input Output HK; OU=Cardano Settlement Layer Server Node; CN=localhost
*  start date: Jul 19 17:31:34 2017 GMT
*  expire date: Jul 19 17:31:34 2027 GMT
*  common name: localhost (matched)
*  issuer: DC=io; DC=iohk; O=Input Output HK; OU=Daedalus Self-Signed Root CA; CN=Daedalus Self-Signed Root CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fee84964da0)
> GET /api/settings/time/difference HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 404 
< date: Thu, 28 Dec 2017 13:31:50 GMT
< server: Warp/3.2.13
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
</pre>
Running the API on the fork build:
<pre>
root@50480d1625b2:/etc/ssl/certs# curl --cacert ca.crt -v https://localhost:8090/api/settings/time/difference
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8090 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: ca.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: DC=io; DC=iohk; O=Input Output HK; OU=Cardano Settlement Layer Server Node; CN=localhost
*  start date: Jul 19 17:31:34 2017 GMT
*  expire date: Jul 19 17:31:34 2027 GMT
*  common name: localhost (matched)
*  issuer: DC=io; DC=iohk; O=Input Output HK; OU=Daedalus Self-Signed Root CA; CN=Daedalus Self-Signed Root CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f39e3b61da0)
> GET /api/settings/time/difference HTTP/1.1
> Host: localhost:8090
> User-Agent: curl/7.52.1
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Thu, 28 Dec 2017 13:43:09 GMT
< server: Warp/3.2.13
< content-type: application/json;charset=utf-8
< 
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
</pre>

The difference is subtle but fatal: the official build returns **404 (Not Found)** while the fork build returns **200 (OK)** and as a consequence Daedalus is stuck on syncing at 100% (see [discussion](https://github.com/input-output-hk/daedalus/issues/603)) 

Is this a know issue? Which branch should be used to build the node? cardano-sl-1.0 is not there anymore:
<pre>
root@43e7e58b48fa:/home/zmeel/cardano-sl# git checkout cardano-sl-1.0
error: pathspec 'cardano-sl-1.0' did not match any file(s) known to git.
</pre>

**Comment by gromakovsky** [comment]
Try using `a267ae05daaf3947fe679eac56d1257a8775b27b` revision of `daedalus` and `master` of `cardano-sl`. Those are last released versions.

**Comment by zmeel** [comment]
@gromakovsky I have build from `master` of `cardano-sl`. The getLocalTimeDifference API is not in `master`.  Is `daedalus` revision `a267ae05daaf3947fe679eac56d1257a8775b27b` not expecting this API?

**Comment by gromakovsky** [comment]
`getLocalTimeDifference` API is a new feature which hasn't been released yet.
`a267ae05daaf3947fe679eac56d1257a8775b27b` shouldn't expect this API.

**Comment by zmeel** [comment]
Oke, thanks! I will give it a try.

 Maybe you guys should clearify in the [build instructions](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) which versions should be build. Now it is suggested to build `cardano-sl-1.0` which does not exist anymore. The build instruction for Daedalus do not specify any branch and therefore I have build from `master` which is not the correct branch.

**Comment by gromakovsky** [comment]
Good catch, thank you, I will ask to update the instruction.

Daedalus should migrate to GitFlow soon and then `master` will be the right branch to use. Currently there is a bit of mess with branches, unfortunately.

**Comment by gromakovsky** [comment]
#2186

**Comment by zmeel** [comment]
I can confirm that building Daedalus revision `a267ae05daaf3947fe679eac56d1257a8775b27b` and cardano-sl `master` build fine and wallet is restoring...

**Comment by gromakovsky** [comment]
Okay, so does everything work for you now? Can we close this issue?

**Comment by zmeel** [comment]
Yes. You can close this issue.
