### ISSUE TITLE
branch to rename

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/cardano-sl#2196]
if the [branch](https://github.com/input-output-hk/cardano-sl/tree/%D0%B1%D0%BB%D1%8F%D0%B4%D0%B1%D0%B6%D0%BE%D0%BF%D0%B0%D1%82%D0%B8%D0%B3%D1%80%D0%B0) is required, I would strongly recommend to rename it. Otherwise delete it at all.

**Comment by gromakovsky** [comment]
It was temporary, not required anymore, deleted.
