### ISSUE TITLE
SSL certificate problem :  Invalid certificate chain

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2234]
I try running a restore command and I get the following 

curl -X POST "https://localhost:8090/api/wallets/restore?passphrase=XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX" -H "accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8" -d "{ \"cwInitMeta\": { \"cwName\": \"string\", \"cwAssurance\": \"CWAStrict\", \"cwUnit\": 0 }, \"cwBackupPhrase\": { \"bpToList\": [ \"string\" ] }}"
curl: (60) SSL certificate problem: Invalid certificate chain

More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by p-alik** [comment]
User `curl`'s `--cacert` option: 
`curl --cacert cardano-sl/scripts/tls-files/ca.crt ...` 

https://github.com/input-output-hk/cardano-sl/blob/develop/scripts/tls-files/ca.crt

**Comment by tanzeelrana** [comment]
Hi @p-alik 

Thanks for the help :) 

I tried the exact same command with the ca cert option but now I get the following error :

curl: (51) SSL: certificate verification failed (result: 5)

**Comment by tanzeelrana** [comment]
Do i need to update the cardano node every time there is an update? 
is there an update on the certificate as well ? 

I had not updated the node in a while so trying to update that and see if that helps.

Steps to reproduce : 

git clone https://github.com/input-output-hk/cardano-sl.git

`curl --cacert cardano-sl/scripts/tls-files/ca.crt -X POST "https://localhost:8090/api/wallets/restore?passphrase=XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX%20XXX" -H "accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8" -d "{ \"cwInitMeta\": { \"cwName\": \"string\", \"cwAssurance\": \"CWAStrict\", \"cwUnit\": 0 }, \"cwBackupPhrase\": { \"bpToList\": [ \"string\" ] }}"`

**Comment by p-alik** [comment]
last update on CA file d77fb7a  on Jul 24, 2017.

> Is it possible that I had to run something before doing this?

Indeed, you have to start `cardano-node`. For testing you could run [demo-with-wallet-api.sh](https://github.com/input-output-hk/cardano-sl/blob/master/scripts/launch/demo-with-wallet-api.sh)

@tanzeelrana, I would recommend to close the issue.

In my opinion https://forum.cardanohub.org is a right place for some sort of questions.
Here is a [thread](https://forum.cardanohub.org/t/cardano-linux-wallet-for-next-week-please/2567/26?u=p-alik) you may be interesting also.

**Comment by tanzeelrana** [comment]
@p-alik  yes I was able to make curl requests and get data as expected thanks ! :)

**Comment by tanzeelrana** [comment]
I am trying to find the right syntax that i can use in . javascript to pass the ca file in a post request :)
