### ISSUE TITLE
Documentation on how to build and run on Windows?

### ISSUE THREAD

**Issue by mohamedmansour** [input-output-hk/cardano-sl#2241]
I am trying to see why the Daedalus wallet doesn't work on my machine, was going to debug and fix it. But I couldn't find a way to build this on Windows, it uses "nix" ?
https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code

Any instructions how to build this and run on Windows?

**Comment by highdev2016** [comment]
Did you find out how to build the Daedalus wallet and run on Windows?
