### ISSUE TITLE
Can I create a gitter channel for this repository?

### ISSUE THREAD

**Issue by CaptJakk** [input-output-hk/cardano-sl#2245]
Hi I'm just looking for a way to contribute to the project. I feel like I have a lot of catching up to do on the code and I was thinking that the more I could chat with developers about how things are laid out if I had questions. I could get up to speed faster. When I looked for it though I didn't see that we already had a gitter channel associated with this project. Is anyone opposed to this? I think that using something like reddit or the community board for this wouldn't be as effective.

**Comment by denisshevchenko** [comment]
You're right, there's no Gitter channel associated with this project. 

> Is anyone opposed to this?

No. :-)

**Comment by CaptJakk** [comment]
I'm thinking that it should be directly associated with either IOHK or Cardano. Since I don't have any access to the repositories or to the organization it may be better for one of the existing members to create it, or, alternatively (I'm not sure what the consensus is), if I could be added to the org than I should be able to do it. Open to further alternatives as well.

**Comment by CaptJakk** [comment]
So I've created a new gitter community called "cardano-dev" and within it I have created a room called "cardano-sl" commensurate with the name of this repo.

Links:
https://gitter.im/cardano-dev
https://gitter.im/cardano-dev/cardano-sl

I will be making a subsequent pull request to include this in the contribution section of the README.md

**Comment by parsonsmatt** [comment]
So #3025 linked to the Telegram channel, but not the Gitter one. Do you think this satisfies this issue?

**Comment by CaptJakk** [comment]
I'd like Gitter, but it seems like we still need to build a critical mass in the community before the fragmented nature of gitter would help more than harm. I'd like to link it just in case since you can tie discussion specifically to different repositories and issues. I was told to remove it in a comment earlier in the tread on #3025

**Comment by SebastienGllmt** [comment]
I would say time to mark this issue as closed.
