### ISSUE TITLE
How to properly generate connect-to-mainnet

### ISSUE THREAD

**Issue by pawelchojnacki** [input-output-hk/cardano-sl#2247]
Everything is happening on current `master`.

I'm trying to set up Cardano + Daedalus on Ubuntu on Ubuntu 17.10. I managed to install `cardano-sl` with `./scripts/build/cardano-sl.sh` as described in https://github.com/input-output-hk/cardano-sl/issues/2235 .

I don't understand how to connect to the main blockchain in a way which would allow Daedalus to read it / create a wallet. Reading `docs/how-to/connect-to-cluster.md` suggests that I should generate `$ nix-build release.nix -A connect.mainnetWallet -o connect-to-mainnet` and be able to run `$ ./connect-to-mainnet`.

I cannot run it with `-A` flag, as it doesn't accept `connect` attribute: `error: attribute ‘connect’ in selection path ‘connect.mainnetWallet’ not found`. I can successfully run it without the flag, with just `-o connect-to-mainnet`.

The problem is, `connect-to-mainnet` generated in such a way is a catalog which doesn't contain any runnable script.

What am I doing wrong here and how should I connect with the mainnet?

**Comment by denisshevchenko** [comment]
@domenkozar Could you help us please?

**Comment by domenkozar** [comment]
Can you try `nix-build -A connectScripts.mainnetWallet -o connect-to-mainnet`

**Comment by domenkozar** [comment]
Fixed by https://github.com/input-output-hk/cardano-sl/pull/2248
