### ISSUE TITLE
ERROR in ./lib/redemption-key-validation.js

### ISSUE THREAD

**Issue by mrazvan22** [input-output-hk/cardano-sl#2260]
Ubuntu 14.04
ghc 8.0.2

I managed to compile cardano and daedalus using stack (following [the guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md)), but when running the daedalus test with `npm run hot-server` I get the following error:

```
ERROR in ./lib/redemption-key-validation.js
Module not found: Error: Cannot resolve module 'bs58' in /home/razvan/src/daedalus/lib
 @ ./lib/redemption-key-validation.js 8:10-25
webpack: Failed to compile.
```

Any ideas? Thanks

**Comment by p-alik** [comment]
It's a daedalus issue. Put it into https://github.com/input-output-hk/daedalus/  

take a look for requirements at https://github.com/input-output-hk/daedalus/blob/master/README.md#development:

> Note: requires a node version >= 4 and an npm version >= 3. This project defaults to 6.x

**Comment by gromakovsky** [comment]
Yes, I agree with @p-alik. Please open an issue in daedalus repository.
