### ISSUE TITLE
Can't connect to SL Api and make it secure

### ISSUE THREAD

**Issue by kiahmed** [input-output-hk/cardano-sl#2262]
Hi,
I am trying to use the SL api from a full node daedalus on Windows. But every legit API calls like below returns nothing with no error. Also I wonder how do I secure the api access with basic auth like other qt-based wallet? Daedalus is deigned differently, I donw know where the fires are and how to configure..any help would be appreciated. Thanks

curl -X GET "http://localhost:8090/api/settings/version" -H "accept: application/json;charset=utf-8"

**Comment by erikd** [comment]
You need to use HTTPS and you probably need to ignore the SSL certificate (at least for now).

On  Linux:
```
> curl -k -X GET "https://localhost:8090/api/settings/version" -H "accept: application/json;charset=utf-8"
{"Right":{"svAppName":{"getApplicationName":"csl-daedalus"},"svNumber":3}}
```

There's no newline at the end of that output so Windows may not display it.

**Comment by kiahmed** [comment]
I did user https..then got nothing at all. Take a look at the postman screen. Also does it supports basic auth or every time
![capture](https://user-images.githubusercontent.com/28849607/34641847-2f6eec20-f2d8-11e7-9be7-aa2b0862c4ea.JPG)
 client has to pass a certificate to make it sercure?

**Comment by erikd** [comment]
Somewhere in the installer there us a file named `ca.crt`.

On Linux, I can do:
```
curl --cacert ~/Daedalux/tls/ca/ca.crt -X GET "https://localhost:8090/api/settings/version" -H "accept: application/json;charset=utf-8"
```

**Comment by gromakovsky** [comment]
Try disabling SSL certificate verification in postman (as suggested by the picture you posted).

**Comment by sharkspeed** [comment]
Could anyone tell me where i can find the ca.crt file as the document said in [docker](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/docker.md)? Is there something wrong?

**Comment by kiahmed** [comment]
@gromakovsky if the server requires a client cert , then disabling from postman how does it helps? either we have to disable it from server or send the right client cert

**Comment by gromakovsky** [comment]
I don't know how it works, but it just works for me.

**Comment by kiahmed** [comment]
are you saying your url still https but you able to connect disabling the certificate?

**Comment by cleverca22** [comment]
there is no client certificates, the `ca.crt` file is to tell the client what root to trust, so the self-signed cert is accepted

under windows, its in a path somewhere close to `c:\program files\daedalus\tls\ca\ca.crt`

**Comment by erikd** [comment]
@kiahmed Yes.

**Comment by SebastienGllmt** [comment]
Try reading this article: https://utopian.io/utopian-io/@h4ck3rm1k3st33m/how-to-use-the-api-from-postman-via-the-swagger-json-on-debian-sid-64bit-gnu-linux
It's for Linux but may be of interest to you.

**Comment by Pastafarianist** [comment]
Apparently this is resolved via @gromakovsky's suggestion. Feel free to reopen if there are any more questions.
