### ISSUE TITLE
Cannot convert undefined or null to object Daedalus Wallet Build 

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2266]
tanzeel@tanzeel01:~/Dev$ git clone https://github.com/input-output-hk/daedalus.git
Cloning into 'daedalus'...
remote: Counting objects: 23469, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 23469 (delta 20), reused 23 (delta 13), pack-reused 23432
Receiving objects: 100% (23469/23469), 17.35 MiB | 1.22 MiB/s, done.
Resolving deltas: 100% (17351/17351), done.
Checking connectivity... done.
tanzeel@tanzeel01:~/Dev$ cd 
cardano-sl/ daedalus/   
tanzeel@tanzeel01:~/Dev$ cd daedalus/
tanzeel@tanzeel01:~/Dev/daedalus$ npm install
npm ERR! Linux 4.10.0-40-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2

npm ERR! Cannot convert undefined or null to object
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tanzeel/Dev/daedalus/npm-debug.log

**Comment by tanzeelrana** [comment]
7271 verbose cwd /home/tanzeel/Dev/daedalus
7272 error Linux 4.10.0-40-generic
7273 error argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
7274 error node v4.2.6
7275 error npm  v3.5.2
7276 error Cannot convert undefined or null to object
7277 error If you need help, you may report this error at:
7277 error     <https://github.com/npm/npm/issues>
7278 verbose exit [ 1, true ]

**Comment by p-alik** [comment]
The issue is misplaced here.
Consider to put it into daedalus repository https://github.com/input-output-hk/daedalus/issues/
