### ISSUE TITLE
You must run this script from the tmux session!

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2267]
[nix-shell:~/Dev/cardano-sl_copy]$ ./scripts/launch/demo-with-wallet-api.sh
+ '[' -n '' ']'
+ echo 'You must run this script from the tmux session!'
You must run this script from the tmux session!
+ exit 1

**Comment by p-alik** [comment]
you have to run the script inside of `tmux` session:

```bash
$ tmux
$ ./scripts/launch/demo-with-wallet-api.sh
```

**Comment by gromakovsky** [comment]
Affirmative. Please run `tmux` first.
