### ISSUE TITLE
Cardano roadmap update

### ISSUE THREAD

**Issue by wiatrM** [input-output-hk/cardano-sl#2322]
Greetings IOHK team!

Maybe this is not good place to post a cardanoroadmap issue, but I will try.
After last update I found that countdown is triggered locally by client script and we could see the contents hours before the countdown ends.

In file `countdown-jan.js` you just triggering

`$('#roadmap-load').addClass('show-version-3');`

To show hidden content.

Do you plan to fix this or somehow shift to server side? A lot of people was angry that roadmap was leaked hours before official countdown.

Regards,
Michal

**Comment by domenkozar** [comment]
This was fixed, thanks.
