### ISSUE TITLE
./connect-to-mainnet: line 34:  6538 Illegal instruction

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2334]
./connect-to-mainnet: line 34:  6538 Illegal instruction     (core dumped) /nix/store/83ia82m8k1dczbiaw5l3vl813k3xyify-cardano-sl-wallet-1.0.3/bin/cardano-node --no-ntp --configuration-file /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/configuration.yaml --configuration-key mainnet_full --web --tlscert state-wallet-mainnet/tls/server.cert --tlskey state-wallet-mainnet/tls/server.key --tlsca state-wallet-mainnet/tls/server.cert --log-config /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/log-config-qa.yaml --topology "/nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/topology.yaml" --logs-prefix "state-wallet-mainnet/logs" --db-path "state-wallet-mainnet/db" --wallet-db-path 'state-wallet-mainnet/wallet-db' --keyfile state-wallet-mainnet/secret.key --wallet-address 127.0.0.1:8090 --ekg-server 127.0.0.1:8000 --metrics +RTS -T -RTS

**Comment by tanzeelrana** [comment]
tanzeel@tanzeel-System-Product-Name:~/cardano-sl$ sudo ./connect-to-mainnet 
[sudo] password for tanzeel: 
Keeping state in state-wallet-mainnet
Launching a node connected to 'mainnet' ...
mkdir: cannot create directory ‘state-wallet-mainnet/tls/’: File exists
Generating a 2048 bit RSA private key
....+++
...............+++
writing new private key to 'state-wallet-mainnet/tls/server.key'
-----
[Attention] We are in PRODUCTION mode
[Attention] Software is built with wallet part
./connect-to-mainnet: line 34:  6718 Illegal instruction     (core dumped) /nix/store/83ia82m8k1dczbiaw5l3vl813k3xyify-cardano-sl-wallet-1.0.3/bin/cardano-node --no-ntp --configuration-file /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/configuration.yaml --configuration-key mainnet_full --web --tlscert state-wallet-mainnet/tls/server.cert --tlskey state-wallet-mainnet/tls/server.key --tlsca state-wallet-mainnet/tls/server.cert --log-config /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/log-config-qa.yaml --topology "/nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/topology.yaml" --logs-prefix "state-wallet-mainnet/logs" --db-path "state-wallet-mainnet/db" --wallet-db-path 'state-wallet-mainnet/wallet-db' --keyfile state-wallet-mainnet/secret.key --wallet-address 127.0.0.1:8090 --ekg-server 127.0.0.1:8000 --metrics +RTS -T -RTS

**Comment by cleverca22** [comment]
@tanzeelrana what does `cat /proc/cpuinfo` say?

**Comment by flyongrass** [comment]
hi，i meet the same problem, how can i fix it?
> cat /proc/cpuinfo 
`
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.18
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.18
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.18
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.18
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 1
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.03
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 1
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.03
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 1
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.03
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 1
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.03
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:
`
