### ISSUE TITLE
how to connect to cardano-sl from external source ?

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2336]
I have port 8090 open to all sorts of traffic but I can not access it from postman or from a browser has someone been able to do it ? 

I have it setup on one of my domains temporarily 

`https://www.pacecouriers.com:8090/api/wallets`

returns me : 

`400 Bad Request`
`The plain HTTP request was sent to HTTPS port`
`nginx/1.10.3 (Ubuntu)`

![image](https://user-images.githubusercontent.com/2520028/34996858-e3b9b6c4-faa8-11e7-8d20-b84b4cf280b1.png)

can someone help please. I do not want to setup a proxy server to redirect my api calls.

I also try curl it from the command line on the server:

`curl --cacert /root/daedalus/tls/ca.crt -X POST "https://pacecouriers.com:8090/api/wallets/restore" -H` `"accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8" -d "{` `\"cwInitMeta\": { \"cwName\": \"string\", \"cwAssurance\": \"CWAStrict\", \"cwUnit\": 0 },` `\"cwBackupPhrase\": { \"bpToList\": [ \"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\",\"x\" ] }}"`

response : 
`<html>`
`<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`<center>The plain HTTP request was sent to HTTPS port</center>`
`<hr><center>nginx/1.10.3 (Ubuntu)</center>`
`</body>`
`</html>`

GET Wallets : 

`curl --cacert /root/daedalus/tls/ca.crt -X GET "https://pacecouriers.com:8090/api/wallets" -H "accept:` `application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8"   --insecure`

response:

`<html>`
`<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`<center>The plain HTTP request was sent to HTTPS port</center>`
`<hr><center>nginx/1.10.3 (Ubuntu)</center>`
`</body>`
`</html>`

sites-enabled/sites-available for nginx I have:

`server {`
`   listen 8090 ssl;`
`    server_name quantumex.ca;`
`    ssl_certificate           /etc/letsencrypt/live/pacecouriers.com/fullchain.pem;`
`    ssl_certificate_key       /etc/letsencrypt/live/pacecouriers.com/privkey.pem;`
`    ssl on;`
`        ssl_session_timeout 5m;`
`        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;`
`        ssl_prefer_server_ciphers on;`
`        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';`
`    location / {`
`      proxy_set_header        Host $host;`
`      proxy_set_header        X-Real-IP $remote_addr;`
`      proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;`
`      proxy_set_header        X-Forwarded-Proto $scheme;`
`      # Fix the “It appears that your reverse proxy set up is broken" error.`
`      proxy_pass          http://127.0.0.1:8090;`
`      proxy_read_timeout  90;`
`    }}`

**Comment by tanzeelrana** [comment]
`curl --cacert /root/daedalus/tls/ca.crt -X GET "https://localhost:8090/api/wallets" -H "accept: application/json;charset=utf-8" -H "Content-Type: application/json;charset=utf-8"  --insecure`

response: 

`curl: (7) Failed to connect to localhost port 8090: Connection refused`

**Comment by gwpl** [comment]
Isn't it web sockets? Therefore `wscat` tool to go?

**Comment by Wayneio** [comment]
@tanzeelrana how did you fix this?
