### ISSUE TITLE
Cardano Explorer API invalid slots order

### ISSUE THREAD

**Issue by samz-me** [input-output-hk/cardano-sl#2430]
I think that slots should be sorted (0 -> 9) the same way as epochs.

![image](https://user-images.githubusercontent.com/2629338/35690721-a70d783c-0787-11e8-8e86-ae818b4b4816.png)

**Comment by gromakovsky** [comment]
Sorry, I don't get it. Epochs are sorted in descending order, slots are also sorted in descending order.

**Comment by Pastafarianist** [comment]
Please reopen if you decide to clarify.
