### ISSUE TITLE
Network.Socket.bind: resource busy (Address already in use)"

### ISSUE THREAD

**Issue by tanzeelrana** [input-output-hk/cardano-sl#2446]
[node:ERROR:ThreadId 313] [2018-02-04 07:02:25.85 UTC] Reporting error with reason "Worker/plugin with logger name LoggerName {getLoggerName = "node"} failed with exception: Network.Socket.bind: resource busy (Address already in use)"

**Comment by domenkozar** [comment]
What OS?

**Comment by tanzeelrana** [comment]
Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-112-generic x86_64)

**Comment by DanielRrr** [comment]
Similar trouble with MacOs Sierra 10.13.3

**Comment by domenkozar** [comment]
That means you already have cardano-sl running somewhere in the background.

**Comment by DanielRrr** [comment]
@domenkozar Thanks! I've already decided the problem.

**Comment by domenkozar** [comment]
So `pkill cardano-node` should be your friend. Please reopen if problem persists.
