### ISSUE TITLE
Thanks for telling me how to build it

### ISSUE THREAD

**Issue by Semafu** [input-output-hk/cardano-sl#2451]
Now tell me how to run it.

and then tell me how to run it at startup.

**Comment by denisshevchenko** [comment]
1. To run local cluster from 4 nodes - use `./scripts/launch/demo-with-wallet-api.sh` from the repo's root.
2. To run node with the real connection to Mainnet - please read it: https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/connect-to-cluster.md
