### ISSUE TITLE
./connect-to-mainnet: line 36: 13154 Illegal instruction

### ISSUE THREAD

**Issue by flyongrass** [input-output-hk/cardano-sl#2472]
### please tell me how can i fix it ?
in  **master branch** , i  run a node with the real connection to Mainnet - refer it: **https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/connect-to-cluster.md**

### when run the script: $ ./connect-to-mainnet , i get the error message like the following:

**./connect-to-mainnet: line 36: 13154 Illegal instruction     (core dumped) /nix/store/f6cjw1a6dz7xzidbvbx7z7iqxnwja86j-cardano-sl-wallet-1.0.3/bin/cardano-node --no-ntp --configuration-file /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/configuration.yaml --configuration-key mainnet_full --web --tlscert state-wallet-mainnet/tls/server.cert --tlskey state-wallet-mainnet/tls/server.key --tlsca state-wallet-mainnet/tls/server.cert --log-config /nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/log-config-qa.yaml --topology "/nix/store/vqyfgdg7i3hdh3q8zp0xx3nrzgja4525-cardano-config/topology.yaml" --logs-prefix "state-wallet-mainnet/logs" --db-path "state-wallet-mainnet/db" --wallet-db-path 'state-wallet-mainnet/wallet-db' --keyfile state-wallet-mainnet/secret.key --wallet-address 127.0.0.1:8090 --ekg-server 127.0.0.1:8000 --metrics +RTS -N2 -qg -A1m -I0 -T -RTS**

### when serach my problem，i found the issue #2334 , refer to the suggestion : 
>$ cat /proc/cpuinfo 

`processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU           E5335  @ 2.00GHz
stepping        : 11
microcode       : 0xbc
cpu MHz         : 1995.093
cache size      : 4096 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm tpr_shadow vnmi flexpriority dtherm
bogomips        : 3990.18
clflush size    : 64
cache_alignment : 64
address sizes   : 38 bits physical, 48 bits virtual
power management:

... ...(other processors like 1,2,3...7 are omitted)
`

**Comment by cleverca22** [comment]
@flyongrass sse4 is required to run the node
