### ISSUE TITLE
Little improvement of stack.yaml

### ISSUE THREAD

**Issue by p-alik** [input-output-hk/cardano-sl#2496]
`$ nix-shell --run ./scripts/build/cardano-sl.sh` throws exception
`You cannot have packages and a shell-file filled at the same time in your nix-shell configuration.`
because `~/.stack/config.yaml` contains
```yaml
nix:
  enable: true
  packages: [zlib.dev, zlib.out]
```
The patch below would solve the issue.
```diff
diff --git a/stack.yaml b/stack.yaml
index 306ea7fad..8d333a1d3 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -119,6 +119,7 @@ packages:
 
 nix:
   shell-file: shell.nix
+  packages: []
 
 extra-deps:
 - ekg-core-0.1.1.3                # https://github.com/tibbe/ekg-core/pull/21
```

**Comment by domenkozar** [comment]
I recommend not having global packages specified, since you'll have to override each project that uses the shell-file.

**Comment by p-alik** [comment]
Sure, it's up to you
