### ISSUE TITLE
Is there a way to run a node with both the explorer and wallet feature

### ISSUE THREAD

**Issue by darxtrix** [input-output-hk/cardano-sl#2661]
For Ethereum, we can run `geth` using which we can both send transactions and read transaction receipts. Is it possible for cardano to run a standalone node with both the `explorer` and `wallet ` feature? 

From the documentation, it seems that we have to run `cardano-node` for the wallet and `cardano-explorer` for the explorer.

Let me know if I am getting something wrong?

**Comment by SebastienGllmt** [comment]
You can see from https://github.com/input-output-hk/cardano-sl/blob/874ed709ff1a200e414eeb805e8d5d26f609a384/scripts/launch/connect-to-cluster/default.nix#L75 which configurations are shared between the wallet and the explorer

**Comment by darxtrix** [comment]
@SebastienGllmt This is really helpful. Closing.
