### ISSUE TITLE
Missing Reference in Wallet Spec

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-sl#2713]
I feel the wallet spec should reference https://arxiv.org/abs/1602.02120 for its bound on union/intersection (or whatever paper this was originally taken from) and possibly also https://eprint.iacr.org/2016/994.pdf given that the bounds mentioned are non-obvious. 

Sorry for being late on this issue. I had forgotten about it until now. I didn't make the PR since I'm not 100% sure is the paper you got this from, but if you want me to make the PR I can do it for you.

@dcoutts @edsko @adinapoli-iohk

**Comment by SebastienGllmt** [comment]
For clarity this comes from https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/docs/spec.tex#L465

**Comment by edsko** [comment]
Ah, yes, @dcoutts has a long list of comments from me somewhere with corrections, and this was one of them. He's way too busy though to implement them and I've since moved on to other stuff. No worries about the PR, I'll cite the paper.

**Comment by edsko** [comment]
This reference is now included in the additions to the spec from https://github.com/input-output-hk/cardano-sl/pull/2617 .
