### ISSUE TITLE
Build sources of 1.1.1 for wallet failed

### ISSUE THREAD

**Issue by TheDevKnight** [input-output-hk/cardano-sl#2762]
Hi, 

when i try to build the sources of the release 1.1.1 ive got this error

`[59 of 67] Compiling Paths_cardano_sl_wallet ( dist/build/autogen/Paths_cardano_sl_wallet.hs, dist/build/Paths_cardano_sl_wallet.o )
[60 of 67] Compiling Pos.Wallet.Web.Methods.Info ( src/Pos/Wallet/Web/Methods/Info.hs, dist/build/Pos/Wallet/Web/Methods/Info.o )
[61 of 67] Compiling Pos.Wallet.Web.Methods ( src/Pos/Wallet/Web/Methods.hs, dist/build/Pos/Wallet/Web/Methods.o )
[62 of 67] Compiling Pos.Wallet.Web.Server.Handlers ( src/Pos/Wallet/Web/Server/Handlers.hs, dist/build/Pos/Wallet/Web/Server/Handlers.o )
/nix/store/jqdysr2sm8v0sqap8i0kd45zw6frgk50-stdenv/setup: line 1044: 25900 Killed                  ./Setup build
builder for '/nix/store/xraym81lr14lan9nqaf5lxqjsa7zb7ny-cardano-sl-wallet-1.1.1.drv' failed with exit code 137
cannot build derivation '/nix/store/wkbzz9vs3fxbyj8s8am7jjg11h3xj8cb-wallet-connect-to-mainnet.drv': 1 dependencies couldn't be built
error: build of '/nix/store/wkbzz9vs3fxbyj8s8am7jjg11h3xj8cb-wallet-connect-to-mainnet.drv' failed`

I use this comand to get the sources `git checkout tags/1.1.1` 
The previous version 1.1.0 could i build without any error. I changed only the tag in my build script. 

But one thing was different, im not sure but it looks like that this time i don't use the binary cache. Because the build takes more time and i also run tests in the build. 

Can someone please verify that the build of 1.1.1 works correct or give my a hint what i must change. 

Regards

**Comment by TheDevKnight** [comment]
One additional info, when i call `curl https://nixos.org/nix/install | sh` nix 2,0 is installed. Is nix 2.0 official supported? Because the [how to](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) build the sl from sources is not up to date (keys for the binary cache).

Can someone pls verify that he can build the master or tags/1.1.1 state from the repo with nix 2.0?

Thanks for every hint.

Regards

**Comment by erikd** [comment]
I've been building cardano-sl with Nix 2.0 successfully. Try the solution offered [here](https://github.com/input-output-hk/cardano-sl/issues/2575#issuecomment-372932138).

**Comment by TheDevKnight** [comment]
Closed, because i could build the sources. The problem was, that i use the linux subsystem for linux. The release 1.0.3 and 1.1.0 works, but 1.1.1 not. I change to a real linux host to build the image and everthing was fine.
