### ISSUE TITLE
Generating Private Keys

### ISSUE THREAD

**Issue by quantumproducer** [input-output-hk/cardano-sl#2777]
Hello,

Where can I find documentation for how a private key is generated + what it involves?

I tried looking at: https://github.com/input-output-hk/cardano-sl/blob/master/wallet/src/Pos/Wallet/Aeson/WalletBackup.hs

Example:

"In Bitcoin, a private key is a 256-bit number, which can be represented one of several ways. Here is a private key in hexadecimal - 256 bits in hexadecimal is 32 bytes, or 64 characters in the range 0-9 or A-F. " from https://en.bitcoin.it/wiki/Private_key

I want to generate a private key by coin flipping so I need to understand how this works.

**Comment by erikd** [comment]
I *think* the code you are looking for is here : https://github.com/input-output-hk/cardano-crypto/blob/master/src/Cardano/Crypto/Wallet.hs#L91. Obviously test everything you are doing very, very carefully :)

**Comment by quantumproducer** [comment]
Thanks @erikd . I saw "n -> Either String XPrv
xprv bs = maybe (Left "error: xprv need to be 128 bytes") (Right . XPrv)"

indicating 128 bytes..  but a seed is only 32 bytes?
generate seed passPhrase
| B.length seed < 32 = error ("Wallet.generate: seed need to be >= 32 bytes, got : " ++ show (B.length seed))

I want to generate a private key by hand then import that into an offline wallet to manage funds.

**Comment by quantumproducer** [comment]
Reopened in https://github.com/input-output-hk/cardano-crypto/issues/37
