### ISSUE TITLE
Please gpg sign releases

### ISSUE THREAD

**Issue by jonathancross** [input-output-hk/cardano-sl#2855]
Given this is financial software which will be targeted by criminals eventually, all releases should be gpg signed.  This is standard practice, here are a few examples:

* Bitcoin [code](https://github.com/bitcoin/bitcoin/releases) and [binaries](https://bitcoin.org/bin/bitcoin-core-0.16.0/) are signed by [laanwj](https://github.com/laanwj) (`0x2346C9A6`)
* [Electrum releases](https://electrum.org/#download) are signed by [ThomasV](https://github.com/ecdsa) (`0x7F9470E6`)
* Monero [code](https://github.com/monero-project/monero/releases) and [binaries](https://getmonero.org/downloads/hashes.txt) are signed by [fluffypony](https://github.com/fluffypony) (`0xC0CDCEB9`)

**Comment by KtorZ** [comment]
This is now done :)
