### ISSUE TITLE
how to get ca

### ISSUE THREAD

**Issue by XieWeiZM** [input-output-hk/cardano-sl#2881]

**Comment by XieWeiZM** [comment]
my java project  want  Connect this service

**Comment by XieWeiZM** [comment]
ava.security.cert.CertificateException: No subject alternative names present

**Comment by XieWeiZM** [comment]
i have import ca  into \jre\lib\security  ,but  erro:
Certificate for <192.168.11.105> doesn't match common name of the certificate subject: localhost

**Comment by XieWeiZM** [comment]
@Edsko de Vries

**Comment by XieWeiZM** [comment]
@avieth

**Comment by KtorZ** [comment]
Duplicate of (https://github.com/input-output-hk/daedalus/issues/912)
