### ISSUE TITLE
Cabal file warning in ... servant-server.cabal: Unknown fields: build-tool-depends (line 128)

### ISSUE THREAD

**Issue by bizlevel** [input-output-hk/cardano-sl#2915]
I prefer resolve all warnings (if it is not ruby or nodejs ))
I still can't build binaries (

Maybe it is important for something.

```
...
Registering cardano-sl-auxx-1.1.1...
cardano-sl-auxx-1.1.1: Test running disabled by --no-run-tests flag.
Completed 2 action(s).
Building cardano-sl-tools

stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=4 --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-tools

Cabal file warning in /home/cardano/cardano-sl/.stack-work/downloaded/TaXW9VrWXFdW/servant-server/servant-server.cabal: Unknown fields: build-tool-depends (line 128)
Fields allowed in this section:
    type, main-is, test-module, buildable, build-tools, build-depends,
    cpp-options, cc-options, ld-options, pkgconfig-depends, frameworks,
    extra-framework-dirs, c-sources, js-sources, default-language,
    other-languages, default-extensions, other-extensions, extensions,
    extra-libraries, extra-ghci-libraries, extra-lib-dirs, includes,
    install-includes, include-dirs, hs-source-dirs, other-modules,
    ghc-prof-options, ghcjs-prof-options, ghc-shared-options,
    ghcjs-shared-options, ghc-options, ghcjs-options, jhc-options,
    hugs-options, nhc98-options
cardano-sl-tools-1.1.1: unregistering (missing dependencies: cardano-sl-wallet)
node-ipc-0.1.0.0: build (lib)
servant-multipart-0.11: configure (lib + exe)
node-ipc-0.1.0.0: copy/register
servant-multipart-0.11: build (lib + exe)
servant-generic-0.1.0.1: configure
...
```

**Comment by erikd** [comment]
> Cabal file warning in /home/cardano/cardano-sl/.stack-work/downloaded/TaXW9VrWXFdW/servant-server/servant-server.cabal: Unknown fields: build-tool-depends (line 128)

That is the cabal version that cardano-sl uses complaining about the cabal file in the "servant-server" project. This is not something that can be fixed by the cardano-sl project other that by upgrading the version of cabal-install we're using. This will happen anyway when we move to the next Stackage LTS version.

**Comment by bizlevel** [comment]
@erikd which version of cabal i must use? Is no requirements i found here (

**Comment by erikd** [comment]
Actually the cabal version does not seem to matter. Not sure where that warning message is coming from (could be cabal, could be GHC, could be stack), but the rest of what I said should be correct.

**Comment by bizlevel** [comment]
ok, i will try previous 2.1 version.

**Comment by erikd** [comment]
The warning is actually not useful. I honestly recommend that you ignore it. Its a warning from a build tool rather than a warning from a compiler.

**Comment by bizlevel** [comment]
I can't ignore it, because building are stopped after that.

**Comment by bizlevel** [comment]
At last i found right version and all is fine.

```
cardano@cardano:~/cardano-sl$ cabal --version
cabal-install version 2.0.0.1
compiled using version 2.0.1.0 of the Cabal library
cardano@cardano:~/cardano-sl$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
cardano@cardano:~/cardano-sl$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.2

```

But after building, all binaries in very different places, and how to collect all them in one place?
Maybe present some script that makes binaries in one place?

Also after i got binaries i can delete all cardano-sl directory? I can use only binary file?
