### ISSUE TITLE
Why api v0 return data wrapped in "Right" Object?

### ISSUE THREAD

**Issue by bigzhu** [input-output-hk/cardano-sl#2934]
[api v0 Doc](https://cardanodocs.com/technical/wallet/api/v0/#) and Swagger file said 

`/api/info` will response like this:

```json
{
  "ciApiVersion": "ApiVersion0",
  "ciSoftwareVersion": {
    "svAppName": {
      "getApplicationName": "string"
    },
    "svNumber": 0
  },
  "ciCabalVersion": {
    "versionBranch": [
      -9223372036854776000
    ],
    "versionTags": [
      "string"
    ]
  },
  "ciGitRevision": "string"
}
```
but master cardano-sl api v0 `/api/info`  call return like this:

```json
{
  "Right": {
    "cabalVersion": "1.1.1",
    "apiVersion": "v0",
    "gitRevision": "aed0d925b",
    "softwareVersion": "cardano-sl:0"
  }
}
```

Data Wrapped in `Right` Object, and struct not like doc said , why?

**Comment by geitir** [comment]
the v0 api is wrapped in "Left" if the request produced an error

**Comment by KtorZ** [comment]
This falls under the flag of "legacy". It can be explained as a direct translation to JSON of the underlying Haskell data-structure (`Either Error Response`). 

Note that V0 has been deprecated a while ago and we highly invite you to rely on V1 from now on.
