### ISSUE TITLE
Question: How to build all in one - Node+Explorer+Wallet API

### ISSUE THREAD

**Issue by bizlevel** [input-output-hk/cardano-sl#2957]
I want to run on one host - Node + Explorer + wallet API.

i can do:
**nix-build -A cardano-sl --cores 0 --max-jobs 2 --no-build-output --out-link master**
or
**nix-build -A connectScripts.mainnetWallet -o connect-to-mainnet**

But it is all different, in first command we have not wallet api on 8090 port. (

How to build all in one?
Or i must run it as separate services,
What build sting will be correct for all or separated build?
Thanks.

**Comment by KtorZ** [comment]
Hi!
The wallet API is actually part of a node. Nodes can be started as _pure_ core nodes (without the API) available, or as edge nodes with the wallet API available; however, they're built together when you simply run:

```
nix-build -A connectScripts.stagingWallet -o connect-to-staging
```

or, preferably, 

```
nix-build -A connectScripts.stagingWallet -o "./launch_$(date -I)_$(git rev-parse --short HEAD)"
```

The explorer is a separated service which is also built separately. You can build it in a similar fashion:

```
nix-build -A connectScripts.stagingExplorer -o "./explorer_$(date -I)_$(git rev-parse --short HEAD)"
```
