### ISSUE TITLE
Lost account and Lost my ADA

### ISSUE THREAD

**Issue by bigzhu** [input-output-hk/cardano-sl#2975]
I create new account and send some ADA to account address.

then cardano-sl is killed by system oom.   restart it, but I can't see my account.

I think  cardano-sl is auto restore wallet and default account or not save my new account.

I still have wallet key, how can I find my account and  ADA in this account?

**Comment by denisshevchenko** [comment]
@bigzhu Please use it for support: https://daedaluswallet.io/faq/#support
