### ISSUE TITLE
Cardano-SL REST API error on /api/v1/node-info 

### ISSUE THREAD

**Issue by webzorg** [input-output-hk/cardano-sl#3019]
`{"status":"error","diagnostic":{"msg":"Something went wrong."},"message":"UnknownError"}`
this is the output of the rest client and this is the output of curl: 
`HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)`

**Comment by TheDevKnight** [comment]
2018-06-01 20:16:33,stdout,[37m:>[0m node-info
2018-06-01 20:16:33,stdout,[37m:>[0m v1
2018-06-01 20:16:33,stdout,[37m:>[0m api
2018-06-01 20:16:33,stdout,[36mGET[0m[37mRequest #33[0m
2018-06-01 20:16:33,stdout,[94m[wallet.api:INFO:ThreadId 15494][0m[2018-06-01 20:16:33.46 UTC] 
2018-06-01 20:16:32,stdout,[31mResponse #32[0m state-wallet-mainnet/logs/node: commitAndReleaseBuffer: invalid argument (invalid character) 0.00300808s

**Comment by webzorg** [comment]
I have extra information about this now. It seems like the syncProgress was stuck at 98%, which made me resync the blockchain. I suspect it may happen in the future too so it would be great to know why the sync may get stuck.

**Comment by TheDevKnight** [comment]
@webzorg i could not confim that. my sync is at 100% and the old api work .../api/settings/sync/progress
I run my node in a docker container ubuntu 16.04. What is your setting?

**Comment by webzorg** [comment]
I'm using api/v1

**Comment by webzorg** [comment]
One more lead.
log output
`data={ syncProgress=100% blockchainHeight=1087971 blocks localBlockchainHeight=1087971 blocks localTimeDifference={ differenceFromNtpServer=-25347[wallet.api:INFO:ThreadId 6672] [2018-06-02 18:45:22.65 UTC] 
    Response #14 state-wallet-mainnet/logs/node: commitAndReleaseBuffer: invalid argument (invalid character) 0.001259398s`

**Comment by TheDevKnight** [comment]
1.2.1 fixed the issue. Can be closed. Thx
