### ISSUE TITLE
How to create a new wallet without using the API

### ISSUE THREAD

**Issue by Josema** [input-output-hk/cardano-sl#3034]
Is it possible to create a new wallet without using the API?  Or the Cardano project will always depends of a node in order to create wallets/accounts/addresses?

I would like to achieve something similar to this to my non-server project: https://iancoleman.io/bip39/

**Comment by Josema** [comment]
The problem is that implementation is in haskell (I guess). I expected to find that implementation in Daedalus (JavaScript is the language I know).

I'd like to implement BIP44 and BIP39 for ADA in my project, but no idea where to find the specification of this.

**Comment by guotie** [comment]
same question.

how to create ada address like 
```
DdzFFzCqrhsoAXTLLcxNGrXLXDMWinfX7CvgaZEbX24ma3KheqyymP5dZtRZmhu8ZV4VtywqxGyTavZJi9wivxzj6oCV9kz4pqUPmVjQ
```

**Comment by KtorZ** [comment]
Daedalus doesn't create addresses nor wallets. It merely creates the initial entropy in the form of mnemonic words using the JavaScript bitcoinjs/bip39 library.
You can create ADA address without the API by using cardano-sl@wallet as a library but it will be Haskell code indeed :)

**Comment by vincenthz** [comment]
@Josema please have a look at https://github.com/input-output-hk/js-cardano-wasm/tree/master/js-example which is effectively a port of the bip39 website to cardano. note that it is just an example/test code.

**Comment by refi93** [comment]
This implementation produces Daedalus compatible wallets, is made in JS: https://github.com/vacuumlabs/cardanolite, and fetches data from the blockchain explorer, so no need to store many data locally.
