### ISSUE TITLE
Problem with the certificate (TLS)

### ISSUE THREAD

**Issue by Josema** [input-output-hk/cardano-sl#3053]
I'm on MacOs and I haven't been able to build the cardano-sl on the master branch. But the version of the develop has been built.

I launch the node by using the script `./scripts/launch/demo-with-wallet-api.sh`. But the API does not work because of the certificate:

```
$ curl -X POST https://localhost:8090/api/v1/wallets \
>   -H "Accept: application/json; charset=utf-8" \
>   -H "Content-Type: application/json; charset=utf-8" \
>   --cacert ./scripts/tls-files/ca.crt \
>   -d '{
>   "operation": "create",
>   "backupPhrase": ["squirrel", "material", "silly", "twice", "direct",
>     "slush", "pistol", "razor", "become", "junk", "kingdom", "flee"],
>   "assuranceLevel": "normal",
>   "name": "MyFirstWallet",
>   "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0"
> }'
curl: (51) SSL: certificate verification failed (result: 5)
```

Tried also `./scripts/tls-files/client.crt` and `./scripts/tls-files/server.crt`.
And why not: `${HOME}/daedalus/tls/ca.crt` and `server.crt`

Same curl (51) error. In all cases.

As the documentation says:
Disable TLS (Not Recommended)
If needed, you can disable TLS by providing the --no-tls flag to the wallet or by running a wallet in debug mode with --wallet-debug turned on.

So I edited the `./scripts/launch/demo-with-wallet-api.sh` and added `WALLET_DEBUG=1`
The node run correctly. And running the same curl command without --cacert:

```
$ curl -X POST https://localhost:8090/api/v1/wallets \
>   -H "Accept: application/json; charset=utf-8" \
>   -H "Content-Type: application/json; charset=utf-8" \
>   -d '{
>   "operation": "create",
>   "backupPhrase": ["squirrel", "material", "silly", "twice", "direct",
>     "slush", "pistol", "razor", "become", "junk", "kingdom", "flee"],
>   "assuranceLevel": "normal",
>   "name": "MyFirstWallet",
>   "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0"
> }'

curl: (35) Server aborted the SSL handshake
```

What am I doing wrong?

**Comment by KtorZ** [comment]
Hey! 
If you're building from develop, you're missing a valid client certificate (`--cert` option on cURL) that is now required. 

I invite you to read this: https://github.com/input-output-hk/cardano-sl/blob/develop/docs/tls-authentication.md

If anything is unclear, your feedback is welcome to improve the current doc :)
