### ISSUE TITLE
`curl` needs `--insecure`

### ISSUE THREAD

**Issue by drandreaskrueger** [input-output-hk/cardano-sl#3129]
Trying out the API, the first command in 
https://cardanodocs.com/technical/wallet/api/v1/#section/Getting-Started/Creating-a-New-Wallet

needs an added `-k` or `--insecure`, otherwise I get this error message:

```
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

so I suggest you change [your first example](https://cardanodocs.com/technical/wallet/api/v1/#section/Getting-Started/Creating-a-New-Wallet) to:

```
curl -X POST https://localhost:8090/api/v1/wallets \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --insecure --cacert ./scripts/tls-files/ca.crt \
  -d '{
  "operation": "create",
  "backupPhrase": ["squirrel", "material", "silly", "twice", "direct",
    "slush", "pistol", "razor", "become", "junk", "kingdom", "flee"],
  "assuranceLevel": "normal",
  "name": "MyFirstWallet",
  "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0"
}'
```

---

versions:

Because [you do not have a Linux wallet yet](https://daedaluswallet.io/#download)  (shocking, really), I had followed the [linux instructions for the beta](https://forum.cardano.org/t/iohk-statement-a-beta-release-for-daedalus-on-linux/10316) , i.e. the `Daedalus-mainnet-installer-1.1.0.960.bin`; and then clone this repo here, to get my hands on the `./scripts/tls-files/ca.crt`. All very very inconvenient. Honestly: Try to think simpler.

**Comment by yihuang** [comment]
Actually, it's very easy to build a wallet node on Linux, I've written a tutorial for this in Chinese:
http://yi-programmer.com/2018-05-30_run-ada-wallet.html

**Comment by drandreaskrueger** [comment]
@yihuang  

http://yi-programmer.com/2018-05-30_run-ada-wallet.html

--->


> This site can’t be reached
> yi-programmer.com’s server IP address could not be found.

**Comment by yanikkoval** [comment]
@drandreaskrueger working now

**Comment by KtorZ** [comment]
Hi, this is incorrect. 
More details on the following links:

- https://github.com/input-output-hk/cardano-sl/blob/develop/wallet-new/README.md#https
- https://github.com/input-output-hk/cardano-sl/blob/develop/docs/tls-authentication.md#using-certificates

**Comment by drandreaskrueger** [comment]
"this is incorrect" is incorrect. 

I'd rather say "we have fixed that"

**Comment by KtorZ** [comment]
No. This was the case when you opened this issue since the tls doc was shipped at the same time.

The wallet README was updates rather recently I admit.

Anyway, hope it works fine for you now :+1:

**Comment by drandreaskrueger** [comment]
> it works fine for you now

No idea. Haven't tried yet. On something else right now.

Thanks anyways.
