### ISSUE TITLE
Unpaid Intern

### ISSUE THREAD

**Issue by abueide** [input-output-hk/cardano-sl#3167]
Sorry this probably isn't the right place for this, but it feels like the best place to post.

Anyways I'm really interested in cardano and I've been studying haskell a lot recently, but I'm lost as to where to start. I'm looking for some one who would be willing to take me as an intern so I can gain some experience working with haskell and contributing to a project. If interested please contact me at abueide@protonmail.com so we can discuss more context behind my motivations and situation, and what we're both looking to gain from the experience.

**Comment by CodiePP** [comment]
Welcome, this is an open source project and everybody may contribute to it.
More details are in [CONTRIBUTING.md](https://github.com/input-output-hk/cardano-sl/blob/develop/CONTRIBUTING.md)

Usually one starts from building the code base [building-from-source](https://cardanodocs.com/for-contributors/building-from-source/). This will probably lead you to beginning using `nix`.
Then, one can run tests (e.g. in module networking: `stack test cardano-sl-networking`), inspect and adapt them, write new ones. If you do not yet have decided on an editor setup, that's the point where one explores all of them to find the one that personally fits best.

There are ways to get involved:
* read and correct documentation (submit your PR on https://github.com/input-output-hk/cardanodocs.com)
* reproduce problems reported in "issues", and report solutions
* if you are on Linux: build and test the "beta" Linux wallet (Daedalus)
* apply your favourite Haskell tool to this code base and report on failure/success
* checkout related projects:
  * [Plutus](https://github.com/input-output-hk/plutus-prototype) smart contract language
  * [Nixops](https://github.com/input-output-hk/iohk-ops) deployment
  * [log-classifier](https://github.com/input-output-hk/log-classifier)
  * [Daedalus](https://github.com/input-output-hk/daedalus) wallet
  * ..
* (hard!) try rebase an older PR on current `develop`
* (fun!) run your own testnet

hope this helps you get started hacking ..

**Comment by abueide** [comment]
@CodiePP I really appreciate your help! I was looking to develop a professional relationship, but I will definitely try to get started on my own soon. I still have quite a bit of haskell to learn before I make any big steps into the project it looks like.
