### ISSUE TITLE
Make ada's address as short as bitcoin's

### ISSUE THREAD

**Issue by yihuang** [input-output-hk/cardano-sl#3186]
Why short address? a short address is very good for UX, and saves spaces in blockchain in the long run.

Currently, Ada's address is both including unnecessary information and too many cbor serialization overheads. I propose a new encoding which can keep the address only a little longer than bitcoin's.

1、Remove derivation path from address (I see rust version already doing this with BIP44 address).
2、Use blake160 rather than blake224 to hash public key (bitcoin use 20 bytes hash), which saves 8 bytes.
3、Remove a level of cbor encoding, which saves 10 bytes.

My proposal is implemented in python already: https://github.com/yihuang/cardano-utils/blob/master/cardano/utils.py#L71

The difference is very huge:
```
old: DdzFFzCqrhsx32JQQd7rKh85WTW8DqEghedsHB9Jv5Z86xKiuFFq9qcHWSyjo9bJwZgaHQoEbzdV1jSHPb1J6EQPHPx933dwHkv6aazr
new: 12MLxfn92bNZvqMcKo3iG7LQ1X1WqooMgadk6cor
```

Decoding code:
```

def decode_addr(s):
    s = base58.b58decode(s)
    if s[0] == 0:
        # version byte for new encoding.
        crc32, = struct.unpack('<I', s[-4:])
        s = s[1:-4]
    else:
        # old normal address.
        tag, crc32 = cbor.loads(s)
        s = tag.value
    assert binascii.crc32(s) == crc32, 'crc32 checksum don\'t match.'
    return cbor.loads(s)
```

**Comment by vincenthz** [comment]
@yihuang thanks for looking into short addresses, but you can't remove the derivation path without changing the way the wallet is working. In this particular case, removing the derivation path would prevent daedalus from finding its own address. a BIP44 compliant wallet, as implemented in the rust library, doesn't indeed need it, so addresses are almost as short as your `new` format there.

* A new address format will be coming with Shelly, which will hopefully resolve the issues you noted, that I have also noted internally already (wasteful CBOR encoding), and also the bad choice of error detection (crc32)
* Once the delegation is live, address will contains the delegation and thus will be longer.

**Comment by yihuang** [comment]
@vincenthz Thanks for your reply, looking forward to Shelly release.

**Comment by zhci** [comment]
@vincenthz Hi, what's the new address format in Shelly? Is any document or source code?

**Comment by vincenthz** [comment]
@zhci you can find the source code here:
https://github.com/input-output-hk/chain-libs/blob/master/chain-addr/src/lib.rs
the doc is currently in another location, but I'll put the doc version with the other low level documentation at https://github.com/input-output-hk/chain-libs/tree/master/chain-impl-mockchain/doc

**Comment by zhci** [comment]
thank you @vincenthz

**Comment by vincenthz** [comment]
most welcome. direct link is now https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/doc/address.md
