### ISSUE TITLE
tmux session  error

### ISSUE THREAD

**Issue by guchenglin111** [input-output-hk/cardano-sl#3517]
pull tag v1.0.3 build success ,then tmux  command  into tmux session!
finally error:
wyx@eth-server-xjp:~/cardano-sl/scripts/launch$ sudo ./demo-with-wallet-api.sh
+ declare WALLET_FLUSH
+ '[' -n '' ']'
+ echo 'You must run this script from the tmux session!'
You must run this script from the tmux session!
+ exit 1

**Comment by guchenglin111** [comment]
wyx@eth-server-xjp:~/cardano-sl/scripts/launch$ tmux
sessions should be nested with care, unset $TMUX to force
wyx@eth-server-xjp:~/cardano-sl/scripts/launch$ sudo ./demo-with-wallet-api.sh
+ declare WALLET_FLUSH
+ '[' -n '' ']'
+ echo 'You must run this script from the tmux session!'
You must run this script from the tmux session!
+ exit 1
wyx@eth-server-xjp:~/cardano-sl/scripts/launch$ tmux
sessions should be nested with care, unset $TMUX to force
wyx@eth-server-xjp:~/cardano-sl/scripts/launch$ sudo ./demo-with-wallet-api.sh
+ declare WALLET_FLUSH
+ '[' -n '' ']'
+ echo 'You must run this script from the tmux session!'
You must run this script from the tmux session!
+ exit 1

**Comment by guchenglin111** [comment]
root@eth-server-xjp:~/cardano-sl/scripts/launch# **sudo** ./demo-with-wallet-api.sh 
+ declare ### WALLET_FLUSH
+ '[' -n '' ']'
+ echo 'You must run this script from the tmux session!'
You must run this script from the tmux session!
+ exit 1
root@eth-server-xjp:~/cardano-sl/scripts/launch# ./demo-with-wallet-api.sh 


root@eth-server-xjp:~/cardano-sl/scripts/launch# /usr/local/dataroot/wyx/cardano-sl/.stack-work/install/x86_64-linux                                          
/lts-11.13/8.2.2/bin/cardano-node-simple  --db-path ./run/logs/node-db1   --rebuild-db  --genesis-secret 1 --listen                                              
127.0.0.1:3001  --json-log=./run/node1.json  --logs-prefix ./run --log-config ./run/conf/node1.log.yaml          --s                             
ystem-start 1535631695 --metrics +RTS -T -RTS --ekg-server 127.0.0.1:8001 --node-id node1 --topology ./run/topology1                                    
.yaml  --update-latest-path ./run/updater1.sh  --update-with-package  --update-server 'http://127.0.0.1:10228/'                                       
[*production*:INFO:ThreadId 4] [2018-08-30 12:21:24.00 UTC] using configurations: ConfigurationOptions {cfoFilePath                                 
= "lib/configuration.yaml", cfoKey = "default", cfoSystemStart = Just 1535631695000000, cfoSeed = Nothing}                                              
[node:ERROR:ThreadId 4] [2018-08-30 12:21:24.00 UTC] logException: ConfigurationParseFailure "lib/configuration.yaml                           
" (InvalidYaml (Just (YamlException "Yaml file not found: lib/configuration.yaml")))                                                                        
cardano-node-simple: ConfigurationParseFailure "lib/configuration.yaml" (InvalidYaml (Just (YamlException "Yaml file                             
 not found: lib/configuration.yaml")))                                                                              
root@eth-server-xjp:~/cardano-sl/scripts/launch#

**Comment by CodiePP** [comment]
there is no need to run the tests as 'root'. You might have compiled the code as user 'wyx'.
start a tmux session: `tmux new-s -s testing`
then, start the test: `./scripts/launch/demo-with-wallet-api.sh`
(you are in the base directory of 'cardano-sl')
