### ISSUE TITLE
how to modify wallet api port ？

### ISSUE THREAD

**Issue by guchenglin111** [input-output-hk/cardano-sl#3528]
1.Machine configuration
OS name:
OS Version: 16.04
CPU speed: 2494Mhz
CPU cores: 2
Physical Memory: 16047 Mgb
Disk install: /dev/vdb1
Disk space total: 492G
Disk space available: 81G
I run the cardano node tag1.3.0

2.When I want modify wallet api port  abvoe

 sudo vim /usr/local/dataroot/wyx/cardano-sl/scripts/launch/run/launcher-config-2.yaml  

nodePath: /usr/local/dataroot/wyx/cardano-sl/.stack-work/install/x87_64-linux/lts-11.13/8.2.2/bin/cardano-node
nodeArgs:
‘’‘……………………’‘
- "--wallet-address"
- "127.0.0.1:88"
- "--system-start"
‘’‘……………………’‘

then  need I  rebuild again?  

any idea what the issue might be? thanks!

**Comment by KtorZ** [comment]
Hi, how do you currently starts the wallet? Are you using nix or stack?
