### ISSUE TITLE
How to get notifications/events about new wallet transactions?

### ISSUE THREAD

**Issue by bazooka70** [input-output-hk/cardano-sl#3560]
Is there a way to get notifications/events about wallet transactions via websockets?
The new API does not seem to mention anything about this.
P.S: I’m using the version 0.11.0

Thanks in advanced.

**Comment by KtorZ** [comment]
Hey!

Indeed, there's no support for websockets event in the new API. Best you can do is to poll the API regularly for transactions. 
There's no plan to support this in the near future (a.k.a next release).
