### ISSUE TITLE
nix-build: command not found

### ISSUE THREAD

**Issue by phpergithub** [input-output-hk/cardano-sl#3844]
1.sh <(curl https://nixos.org/nix/install) --daemon

Alright! We're done!

Before Nix will work in your existing shells, you'll need to close
them and open them again. Other than that, you should be ready to go.

Try it! Open a new terminal, and type:

  $ nix-shell -p nix-info --run "nix-info -m"

Thank you for using this installer. If you have any feedback, don't
hesitate:

2.nix-build -A cardano-sl-node-static --out-link master
nix-build: command not found

**Comment by rvl** [comment]
Hello.
- Did you close your terminals and open them again before running `nix-build`?
- What shell are you using?
- Do you have any custom shell config that would prevent `source ~/.nix-profile/etc/profile.d/nix.sh` from being run when the shell starts?
