### ISSUE TITLE
./scripts/build/cardano-sl.sh fails

### ISSUE THREAD

**Issue by phpergithub** [input-output-hk/cardano-sl#3853]
remote: Total 217 (delta 0), reused 0 (delta 0), pack-reused 217
Receiving objects: 100% (217/217), 37.51 KiB | 163.00 KiB/s, done.
Resolving deltas: 100% (95/95), done.
Cloning fa925f9dadf239b38e2ffcc35f9d241a9fcb7d55 from https://github.com/input-output-hk/log-warper.git
Cloning into '/opt/ada/cardano-sl/.stack-work/downloaded/DOh1FXO6uJXI'...
remote: Enumerating objects: 1837, done.
remote: Total 1837 (delta 0), reused 0 (delta 0), pack-reused 1837
Receiving objects: 100% (1837/1837), 432.34 KiB | 465.00 KiB/s, done.
Resolving deltas: 100% (1125/1125), done.
Cloning 1049699df411c9584523ba7424cba1f3f82ac419 from https://github.com/serokell/acid-state.git
Cloning into '/opt/ada/cardano-sl/.stack-work/downloaded/r7roAoD-OTIb'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1383 (delta 0), reused 3 (delta 0), pack-reused 1377
Receiving objects: 100% (1383/1383), 281.84 KiB | 235.00 KiB/s, done.
Resolving deltas: 100% (642/642), done.
Cloning 2c9e51804e8217dff89f5c32cbe0d79ce20bc508 from https://github.com/input-output-hk/haskell-hedgehog.git
Cloning into '/opt/ada/cardano-sl/.stack-work/downloaded/27pmaoPEDNVl'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 1439 (delta 7), reused 17 (delta 5), pack-reused 1415
Receiving objects: 100% (1439/1439), 393.29 KiB | 419.00 KiB/s, done.
Resolving deltas: 100% (778/778), done.
Please ensure that commit 2c9e51804e8217dff89f5c32cbe0d79ce20bc508 exists within https://github.com/input-output-hk/haskell-hedgehog.git
Running /nix/store/6lkl4g8jbg0m4fgl5s1jclafic2k6lhx-git-2.16.2/bin/git --git-dir=.git reset --hard 2c9e51804e8217dff89f5c32cbe0d79ce20bc508 -- in directory /opt/ada/cardano-sl/.stack-work/downloaded/27pmaoPEDNVl/ exited with ExitFailure 128

fatal: Could not parse object '2c9e51804e8217dff89f5c32cbe0d79ce20bc508'.

**Comment by KtorZ** [comment]
Hey! 
Using this script is deprecated and highly not recommended. It will be removed soon enough. Instead, please refer to the following guide should you want to build cardano-sl from sources:

https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
