### ISSUE TITLE
the block sync stop at 1813887 

### ISSUE THREAD

**Issue by bitcodernull** [input-output-hk/cardano-sl#3865]
the error log : 
Failed to verify blocks: failure: [block's size exceeds limit (632.902 KiB > 32 KiB)]

**Comment by got3nks** [comment]
Same here:

```
[node:ERROR:ThreadId 600] [2018-11-18 14:52:12.03 UTC] failure: [block's size exceeds limit (632.902 KiB > 32 KiB)]
[reporter:ERROR:ThreadId 600] [2018-11-18 14:52:12.64 UTC] Reporting error with reason "blockCreator failed: Cardano fatal error: failure: [block's size exceeds limit (632.902 KiB > 32 KiB)]{ nodeIps: '[]', peers: 'OutboundQ internal state '{Peers {peersRoutes = Routes {_routesCore = [], _routesRelay = [[NodeId 13.115.1.223:3000:0]], _routesEdge = []}, peersClassification = fromList [(NodeId 13.115.1.223:3000:0,NodeRelay)]}}'' }"
[reporter:INFO:ThreadId 600] [2018-11-18 14:52:12.64 UTC] sendReportNodeImpl: not sending report because no reporting servers are specified
```

**Comment by testtkxxd** [comment]
same

**Comment by hunjixin** [comment]
same

**Comment by got3nks** [comment]
Version 1.3.2 has been released. I'm compiling it now

**Comment by testtkxxd** [comment]
1.3.2 fix it

**Comment by dogpatchmedia** [comment]
I have 1.3.2 and i still get this error.

**Comment by shabbir-bblab** [comment]
I'm getting same error and my cardano-sl version is 1.1.1. I want to update Cardano-SL but i don't have 12 word phrase. If i upgrade then i won't be able to restore my current wallet and ADA, right?

**Comment by shabbir-bblab** [comment]
KtorZ please help us.

**Comment by erikd** [comment]
@shabbir-bblab The reason you can't sync beyond that block is because you have not upgraded Daedalus. You should take a complete backup of the current wallet system and then upgrade. If the worst happens and the upgrade goes wrong, then you still have the backup and can try again.

Also @KtorZ is a developer on this project and probably not an expert on support issues like this. For support: https://iohk.zendesk.com/hc/en-us

**Comment by shabbir-bblab** [comment]
Thank you for the help @erikd 
But i have no Daedalus, I'm only running Cardano-sl backend node which is connected to mainnet, and calling wallet APIs from either curl or java code.

**Comment by erikd** [comment]
@shabbir-bblab My answer still applies for just the cardano node.
