### ISSUE TITLE
Cannot find getter associated with this version number

### ISSUE THREAD

**Issue by melvjoshua** [input-output-hk/cardano-sl#3885]
Hello, I have some trouble after upgrade my wallet to Cardano v1.3.2..

Here is the screenshot of error..
![photo_2018-11-22_15-38-59](https://user-images.githubusercontent.com/13884709/48890974-d7406380-ee6c-11e8-80d4-244d99564399.jpg)

Step of upgrade..
1. cd cardano-sl
2. git checkout master
3. git pull
4. nix-build -A connectScripts.mainnet.wallet -o connect-to-mainnet-1.3.2

What must I do to solve this problem?

**Comment by dcoutts** [comment]
Thanks. We have identified the problem and are working on a patch.
