### ISSUE TITLE
unable to restore account

### ISSUE THREAD

**Issue by harvyh1985** [input-output-hk/cardano-sl#3898]
I have a wallet from cardano-sl run in a centos 7 machine,but the disk which saved data was broken,so i want to restore the wallet and account,my wallet only contain on account and some addresses in it.
First of all i post in to /api/v1/wallets with correct data,the response is "syncState":{"tag":"restoring"} and i wait for a few minutes,it change to "tag":"synced".
The next step  i use my accountindex  from the broken machine post to /api/v1/wallets/Aexxx/accounts/3572****,but its return a message "Request error (No account with id)".
I checked the accounts restored from /api/v1/wallets/Aexx/accounts,there have on account but not equal the accountindex from the broken machine.
So how can i get my account and ADA restored ?

**Comment by rvl** [comment]
Hello @harvyh1985 , are you able to successfully restore your accounts with the latest release [2.0.1](https://github.com/input-output-hk/cardano-sl/releases/tag/2.0.1)?

**Comment by vhulchenko-iohk** [comment]
There has been no feedback on this issue from the requesters for almost a year, so I'm closing it.

**Comment by vhulchenko-iohk** [comment]
There has been no feedback on this issue from the requesters for almost a year, so I'm closing it.
