### ISSUE TITLE
Wallet API (1.3.2):  "validationError": "Error in $: not enough input" 

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/cardano-sl#3915]
When trying to create "accounts" and when trying to send a transaction via the API using CURL, I get this error about the input not being enough. There is no clarification in the documentation about what this error actually means. 

I have made sure that addresses are correct, that the spending password is exactly 64 bytes, that the funds are denominated in lovelaces, and I even send it to the API as a JSON array just to be extra sure it likes what its getting from me. And every time, its always that the input is not enough. what does that even mean?!

**Comment by KtorZ** [comment]
Hi, can you elaborate a bit on your actual request (leave out passwords and sensitive information):

- Exact endpoint / url ?
- Request body ?
- Associated headers ?

And finally, which documentation are you referring to?

**Comment by dogpatchmedia** [comment]
Hi. Thanks for your interest in helping with this, here are the answers to your questions:

> * Exact endpoint / url ?

Local node, when trying to send a transaction or check the fees or create an address all of these end points return the same results: Array ( [status] => error [diagnostic] => Array ( [validationError] => Error in $: not enough input ) [message] => JSONValidationFailed )

http://127.0.0.1:8090/api/v1/transactions
http://127.0.0.1:8090/api/v1/transactions/fees
https://127.0.0.1:8090/api/v1/addresses

> * Request body ?

For the request body, I follow the documentations examples. But it doesn't seem to matter what order you put the elements in, its always not enough input. But it goes something like this (where $source and $destination are JSON arrays as input requires, and sometimes I include $groupPolicy just to see if that makes a difference, it doesnt):

/api/v1/transactions?source='.$source.'?destination='.$destination.'?spendingPassword='.$spendingPassword)

> * Associated headers ?

$headers = [
            "Cache-Control: no-cache",
            "Content-Type: application/json;charset=utf-8",
            "Postman-Token: b71b609e-e028-d78b-ce51-3d0ec0b5c9fb",
            "accept: application/json;charset=utf-8"        
        ];

> 
> And finally, which documentation are you referring to?

API documentation: https://cardanodocs.com/technical/wallet/api/v1/ 

Those are the only API documents I know about, unless there is something else that I dont know about.

Ok, hope any of this helps. I also[ posted it on the official Cardano forum](https://forum.cardano.org/t/api-post-to-transaction-endpoint-responds-with-not-enough-input/18193/9) as well. Thanks!

**Comment by KtorZ** [comment]
Hi, you need to send valid `application/json` objects. For instance (cf the documentation):

```
curl -X POST https://localhost:8090/api/v1/transactions \
  -H "Accept: application/json; charset=utf-8" \
  -H "Content-Type: application/json; charset=utf-8" \
  --cacert ./scripts/tls-files/ca.crt \
  -d '{
  "destinations": [{
    "amount": 14,
    "address": "A7k5bz1QR2...Tx561NNmfF"
  }],
  "source": {
    "accountIndex": 0,
    "walletId": "Ae2tdPwUPE...8V3AVTnqGZ"
  },
  "spendingPassword": "5416b2988745725998907addf4613c9b0764f04959030e1b81c603b920a115d0"
}'
```

It seems that you're sending your request in a `application/x-www-form-urlencoded` which isn't valid (especially if you tell the server you're sending it `application/json` :upside_down_face: ... ).

Make sure to carefully read the examples from the documentation, for instance:

https://cardanodocs.com/technical/wallet/api/v1/#section/Getting-Started/Sending-ADA

**Comment by dogpatchmedia** [comment]
I don't feel like this is closed. My problem hasn't been solved and you've done nothing to help other than to paste a page from the manual that Ive read a 1000 times and then included a snarky comment with no explanation as to how and why you have come to that conclusion. 

I don't understand where your getting the `application/x-www-form-urlencoded` it doesn't say that in the headers. Maybe you could explain instead of just assuming?

**Comment by KtorZ** [comment]
Apologies for the abruptness, we've quite many things to manage and I've closed this to better kep track of issues. There's no actual issue beside your request being malformed as explained in my previous comment.

Your request payload as shown here:

```
/api/v1/transactions?source='.$source.'?destination='.$destination.'?spendingPassword='.$spendingPassword)
```

is urlencoded. Hence my deduction. You should be using a JSON format that goes in the request body, and not url. This will solve your issue :)

**Comment by dogpatchmedia** [comment]
I dont understand. the source, and destination ARE JSON ALREADY! they are already sent as JSON, encoded as JSON just to be double extra sure. 

the source IS JSON ALREADY! Ive been through this, a hundred times.
```

$j_source 		= '{"accountIndex":' . $wallet_idx . ',"walletId": "'. $wallet_id . '"}'; 
$j_destination	= '{"address":"' . $banker . '","amount":' . $lovelace . '}';

```
as is, it gives an error about needing an array and getting a string hence we do this to give it an array:

```
$source 		= json_decode($j_source, true); // object = false, array = true
$destination 	= json_decode($j_destination, true); // object = false, array = true
```

i dont understand why thats not correct! ive giving it exactly what it wants, a JSON array in JSON format. yet, its always not enough input.

**Comment by KtorZ** [comment]
Hi, 
You aren't sending JSON serialized data to the wallet backend but urlencoded strings. Unfortunately, this doesn't happen automatically when setting the `Content-Type` header, this is just a mechanism to tell the server what kind of data you're sending and how the server should interpret it. 

Please, refer to the following SO answer about sending JSON payloads in PHP using curl:

https://stackoverflow.com/questions/6213509/send-json-post-using-php
 
I hope this will help.

**Comment by dogpatchmedia** [comment]
Thanks for the help, its much appreciated. 

However.. Im pretty sure Ive done all that correctly with the CURL, mine looks exactly like the examples and it still doesnt work. I dont see any difference besides that i used the curl_setopt options instead of traditional vars.

```
// CURL Post
    private function post(string $endPoint, $postFields = [])
    {
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $this->host.$endPoint);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_PORT, $this->port);
        curl_setopt($ch, CURLOPT_ENCODING, "");
        curl_setopt($ch, CURLOPT_MAXREDIRS, 10);
        curl_setopt($ch, CURLOPT_TIMEOUT, 30);
        curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($postFields));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSLCERT, Cardano::CERT_PATH);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'POST');


        $headers = [
            "Cache-Control: no-cache",
            "Content-Type: application/json; charset=utf-8",
            "Postman-Token: b71b609e-e028-d78b-ce51-3d0ec0b5c9fb",
            "Accept: application/json; charset=utf-8"        
        ];
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $data = curl_exec ($ch);
        $this->httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        
        if(curl_exec($ch) === false)
        {
            throw new Exception('Curl error: ' . curl_error($ch));
        }
        curl_close ($ch);
        return $data;
    }
```

**Comment by dogpatchmedia** [comment]
I give up. nothing works. no matter how i format it, its always not enough input.

ive started from scratch 19543908647850667954329 times and its always the same results: NOT ENOUGH INPUT! 

Ive followed 20 different CURL PHP POST JSON tutorials, Ive read several hundred worthless SO questions. Ive read article after article and nothing works.

Either every single post and tutorial online is wrong, or there is something seriously borked here.
