### ISSUE TITLE
"validationError": "Error in $.destinations: expected NonEmpty a, encountered Object" 

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/cardano-sl#3945]
Hi.

Is that "a" supposed to be "array?" and also what does this mean? Ive done is_object on everything and its all false so no objects in sight...

This happens when trying to send a transaction to /api/v1/transactions and  /api/v1/transactions/fees

**Comment by MarcFontaine** [comment]
Hi,
`NonEmpty a` is the same as `NonEmpty x`. `x` and `a` are variables like for example in `sqrt(x)` or `sin(a)` or `foo=a+x` 
`NonEmpty a` means non empty list of some element of type `a` without saying at this point what `a` is.
I guess this message says there was an error when validating data that has been received.
It is not directly related to running `is_object` on the client side.

**Comment by dogpatchmedia** [comment]
I dont understand why a request to the transactions end point to make a transaction (post) is any different than on to say create a wallet (post) or create an account (post) or address (also post). They all require similar input, a mix of arrays and strings. So I really dont undertstand why there is suddenly a error. seriously the only difference is that it wants 2 arrays, source and destination and create wallet only wants one. i just dont get it. i would really appreaciate some actual help instead of snarky comments or restating of the documentation, just come on man, i need help. this has been a problem for like a week.

**Comment by MarcFontaine** [comment]
Hello,  I'm not a PHP expert but i think your destinations is only one address/amount pairs while it should be an array of address/amount pairs..A transaction can pay to a list of receivers.

**Comment by dogpatchmedia** [comment]
> Hello, I'm not a PHP expert but i think your destinations is only one address/amount pairs while it should be an array of address/amount pairs..A transaction can pay to a list of receivers.

I think i understand what your saying, the documentation does only refer to it as sending to multiple people at once and never just a 1-to-1 transaction its always 1-to-many (ie, an array of destinations).

So I thought it would be ok to send it to one person just using a single element array (a sender and the amount), but clearly that didnt work.

So how do you send to a single person? 

Should I just include a second or third blank or empty transaction to make it a group thing?

All I want for Christmas is better API documentation... hahah

**Comment by MarcFontaine** [comment]
My approach for doing this in PHP would be to download the curl examples from the documentation and print the output  of `json_encode($post_fields)` to stdout. Both must have exactly the same structure.
If there are nested blocks of `{...{...}..}` in the example the request must have exactly the same structure.
