### ISSUE TITLE
[PROBABLY BUG]Blockchain location isn't static

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-sl#3983]
The place, when node stores its data, depends on dir, when user was, when started cardano-node.
Steps to reproduce:
0) let cardano dir be ~/git/cardano-sl
1) try to connect to cluster, doesn't matter which one, I connect it to staging one
```
cd ~/git/cardano-sl
./connect-to-staging
```
2) stop it
3) we got a new dir:  ~/git/cardano-sl/state-wallet-staging
4) go to another folder, let it be ~/git
`cd ~/git`
5) then launch it again with a relative or absolute path, doesn't matter:
```
./cardano-sl/connect-to-staging
```
6) stop it
7) `ls -l`
8)  there is another 'state-wallet-staging', but not in 'cardano-sl' dir.

**Comment by rvl** [comment]
Hello @Fell-x27, thanks for your report. This is by design. If launching your wallet with systemd (for example) you can set a [working directory](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Paths).
