### ISSUE TITLE
Can not run cardano-sl on testnet

### ISSUE THREAD

**Issue by tranchiendang** [input-output-hk/cardano-sl#3991]
I try to build and run cardano-sl, but getting those errors, any suggestion how to fix them
Command to build `nix-build -A connectScripts.testnet.wallet.x86_64-linux -o "./launch_$(date -I)_$(git rev-parse --short HEAD)" -v`

Error

> Wallet is starting...[cardano-sl.*production*:Info:ThreadId 5] [2019-01-04 17:17:09.19 UTC] using configurations: ConfigurationOptions {cfoFilePath = "/nix/store/k5fcy5cyba6gjrpgy8jwv0shmnn3l7a3-cardano-sl-config/lib/configuration.yaml", cfoKey = "testnet_full", cfoSystemStart = Nothing, cfoSeed = Nothing}
> [cardano-sl.*production*:Info:ThreadId 5] [2019-01-04 17:17:09.56 UTC] System start time is 1537941600000000
> [cardano-sl.*production*:Info:ThreadId 5] [2019-01-04 17:17:09.56 UTC] Current time is 1546622229562699
> [cardano-sl.*production*:Info:ThreadId 5] [2019-01-04 17:17:09.56 UTC] initalizing user secret
> [cardano-sl.node:Error:ThreadId 5] [2019-01-04 17:17:09.56 UTC] logException: flock: invalid argument (Bad file descriptor)
> cardano-node: flock: invalid argument (Bad file descriptor)

**Comment by rvl** [comment]
Hi, it seems to be unable to create a lockfile for the DB. What filesystem are you using?

Does it work if you run it from `/tmp`? (This means that the state directory will be stored at `/tmp/state-wallet-testnet`). For example:
```
cd /tmp
/path/to/cardano-sl/launch_2019-01-05_6a1334486
```

**Comment by rvl** [comment]
Thanks for the info.
1. What does `mount` say? (This will show the types of the mounted filesystems)
2. There might have been an error when creating the lock file `./state-wallet-testnet/secret.key.lock`. What does `ls -l ./state-wallet-testnet` say?
3. Does the [`flock`](http://manpages.ubuntu.com/manpages/xenial/man1/flock.1.html) command work? `flock ./state-wallet-testnet/test.lock sleep 2`
3. Could you run the node under `strace` to show if there was an error opening the lock file?
   ```
   strace -e trace=desc -ff /path/to/cardano-sl/launch_2019-01-05_6a1334486 2> strace.txt
   grep lock strace.txt | less
   ```
   (look for `state-wallet-testnet/secret.key.lock` in `strace.txt`)

**Comment by tranchiendang** [comment]
It worked bro. I rebuilt with changing the directory of state-wallet-testnet to /tmp.
Thank you very much.
