### ISSUE TITLE
Error: No Account with id (wallet_id)

### ISSUE THREAD

**Issue by dogpatchmedia** [input-output-hk/cardano-sl#4039]
I did a pull on the latest master branch and now I get this error:

`Request error (No account with id *wallet_id*@0 found)`

Where the *wallet_id* can be any wallet ID on the local node (either an existing one or a newly created one)

When you query the API for anything that involves a wallet_id you'll get this error.

When you try and lookup the wallets on the node via the API, the "data" payload comes back empty: 

`{"data":[],"status":"success","meta":{"pagination":{"totalPages":1,"page":1,"perPage":50,"totalEntries":0}}}`

Ive tried to rollback the node to previous commits, but I still get the same issue.

**Comment by dogpatchmedia** [comment]
I figured out how to fix it. If anybody else comes across this issue, heres 2 tips:

1. rebuild the connect-to-mainnet script after you pull and build any new updates.
2. run the [*internal* API ](https://cardanodocs.com/technical/wallet/api/v1/#tag/Internal) call for *apply_update* after you pull and build any new updates to be sure if any changes to the wallet format or anything else has been done that your node  will update your wallet to the new specs.

**Comment by crcrcr999** [comment]
Same issue,but I've fail by use the tips2.

**Comment by rvl** [comment]
Tip 1 might help.

Tip 2 won't help. This internal API is only used for the Daedalus update system. It will not migrate the wallet DB. The DB migration happens automatically when running the new version. Addtionally, after the 2.0.0 update, it will begin a restore of existing wallets. This may be the cause of `WalletNotFound`.

We can follow up in #4091.
