### ISSUE TITLE
Can't build neither master nor v1.0.3 with nix

### ISSUE THREAD

**Issue by utgarda** [input-output-hk/cardano-sl#4080]
Tried to follow this manual: https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md
didn't go past running `nix-build`, let me know if I can get you more info.

```
$ uname -a
Linux jotunheim 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64 GNU/Linux
$  ~ nix --version
nix (Nix) 2.2.1
$  ~ nix-build --version
nix-build (Nix) 2.2.1

$ git status
On branch master
Your branch is up to date with 'origin/master'.
$ git rev-parse HEAD
c6a50c2a736d72da6be93072b9d627407e4d957e

$ nix-build -A cardano-sl-node-static --out-link master
...
error: while setting up the build environment: getting attributes of path '': No such file or directory
```
[nix_build_master_cadano-sl-node-static.log](https://github.com/input-output-hk/cardano-sl/files/2872205/nix_build_master_cadano-sl-node-static.log)

Same for 1.0.3:
```
$ git checkout v1.0.3
HEAD is now at e4b77ed9d Merge pull request #1842 from input-output-hk/gromak/set-cabal-versions-1.0.3
$ git rev-parse HEAD
e4b77ed9d8502a181fb1584b9f48984ba1399598
$ nix-build -A cardano-sl-node-static --out-link v103 &> ./nix_build_v1.0.3_cadano-sl-node-static.log
```
[nix_build_v1.0.3_cadano-sl-node-static.log](https://github.com/input-output-hk/cardano-sl/files/2872206/nix_build_v1.0.3_cadano-sl-node-static.log)

**Comment by rvl** [comment]
Hello @utgarda,

v1.0.3 will never build with Nix 2.x.

I am able to build `cardano-sl master` with Nix 2.2pre6600_85488a93.

I have not seen that error before, but it looks like someone else has recently: NixOS/nix#2673

Try running `nix doctor` to see whether it reports any problems.

I notice that you have not configured the IOHK binary cache. Without it, your build will take a really long time. There are instructions here: https://github.com/input-output-hk/cardano-sl/blob/master/docs/nix.md
Enable the IOHK binary cache (and restart `nix-daemon`) before doing anything else.

**Comment by vhulchenko-iohk** [comment]
There has been no feedback on this issue from the requesters for almost a year, so I'm closing it.
