### ISSUE TITLE
Getting errors while trying to Build and run in the nix store

### ISSUE THREAD

**Issue by sneha6patel** [input-output-hk/cardano-sl#4088]
I'm performing this following code and it's getting errors.
`nix-build -A connectScripts.mainnet.wallet -o "./launch_$(date -I)_$(git rev-parse --short HEAD)"`

Please refer the following screenshot.
![001](https://user-images.githubusercontent.com/47587639/53163704-ae0eab00-35f4-11e9-88f4-7daf63a6c547.png)

**Comment by rvl** [comment]
Hello, it's best to enable the IOHK binary cache before building. Otherwise it will take a really long time. Instructions are here: https://github.com/input-output-hk/cardano-sl/blob/master/docs/nix.md
