### ISSUE TITLE
How to do request with SSL connection certificate in cardano testnet?

### ISSUE THREAD

**Issue by sneha6patel** [input-output-hk/cardano-sl#4090]
I've used this following code :

    curl --cacert ./state-wallet-mainnet/tls/client/ca.crt https://localhost:8090/api/settings/sync/progress

But It's getting following errors:

curl: (35) gnutls_handshake() failed: Error in the push function.

**Comment by rvl** [comment]
Add `--cert ./state-wallet-mainnet/tls/client/client.pem` to your `curl` command.

**Comment by sneha6patel** [comment]
Thank you.. It's solved.
