### ISSUE TITLE
API doesn't work

### ISSUE THREAD

**Issue by Fell-x27** [input-output-hk/cardano-sl#4119]
1) I have installed the cardano-sl with a fresh installation, so it says that it's a
`cardano-node-3.0.1, git revision 57a0d236eed59c48214ee70128549d6cfdbc73db`
2) I've launched it as previous I did, with connect-to-mainnet script and everything was OK
3) I'm trying to call it with API:
`curl -X GET https://localhost:8090/api/v1/node-info -H 'Accept: application/json;charset=utf-8' --cacert state-wallet-mainnet/tls/client/ca.crt --cert state-wallet-mainnet/tls/client/client.pem`

It was working on the previous version, but now it says:
`curl: (35) error:0407008A:rsa routines:RSA_padding_check_PKCS1_type_1:invalid padding`

I checked the documentation and found, that there is new API version 1.4.1 with a different certs paths:
`curl -X GET https://localhost:8090/api/v1/node-info -H 'Accept: application/json;charset=utf-8' --cacert ./scripts/tls-files/ca.crt --cert ./scripts/tls-files/client.pem `

But there is the same error.

The Node starts with follows certs flags:

```
 --tlscert state-wallet-mainnet/tls/server/server.crt                         
 --tlskey state-wallet-mainnet/tls/server/server.key                          
 --tlsca state-wallet-mainnet/tls/server/ca.crt 
```

Is it a bug, or I'm just doing smth wrong?

**Comment by Fell-x27** [comment]
Well, on the morning the node just stopped.
I've launched it and...sync status is 0, but API is working.

**Comment by cleverca22** [comment]
there should also be a bash script called `curl` inside `state-wallet-mainnet` that deals with the certs for you

just run it with `api/v1/node-info` for example
