### ISSUE TITLE
can't make API requests when running on systemd

### ISSUE THREAD

**Issue by hiramf** [input-output-hk/cardano-sl#4126]
I've been following this [tutorial](https://forum.cardano.org/t/running-a-cardano-sl-node-on-testnet/21530) with some modifications. Instead of using `rc.local`, I'm using `systemd` to run `connect-testnet-wallet` as a service (I'm also not using root).

This request works perfectly when executing `./connect-testnet-wallet` from the terminal: 
```
curl -v --cacert ./state-wallet-testnet/tls/client/ca.crt --cert ./state-wallet-testnet/tls/client/client.pem https://localhost:8090/api/v1/node-info
```

However, when starting the service (`sudo systemctl start cardano-sl`), it will not work and returns this error:
```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8090 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: ./state-wallet-testnet/tls/client/ca.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* error:04067084:rsa routines:rsa_ossl_public_decrypt:data too large for modulus
* stopped the pause stream!
* Closing connection 0
curl: (35) error:04067084:rsa routines:rsa_ossl_public_decrypt:data too large for modulus
```

This is what my service file looks like: 
```
After=network.target

[Service]
ExecStart=/home/johndoe/cardano-sl/connect-testnet-wallet
Restart=always

[Install]
WantedBy=multi-user.target
```

Why would running the node as a systemd service cause the TLS certificates not to work (if that's indeed the problem)?

**Comment by cleverca22** [comment]
does your user still have permission to read the tls files? what user owns them when you look at it with `ls -l` ?

**Comment by hiramf** [comment]
```
johndoe@pc:~$ ls -l cardano-sl/state-wallet-testnet/tls/client/
total 20
-rw------- 1 johndoe johndoe 1199 Apr  7 18:23 ca.crt
-rw------- 1 johndoe johndoe 1199 Apr  7 18:23 client.crt
-rw------- 1 johndoe johndoe 1678 Apr  7 18:23 client.key
-rw------- 1 johndoe johndoe 2878 Apr  7 18:23 client.pem
```

**Comment by cleverca22** [comment]
you dont have a `WorkingDirectory` set in the `.service` file, and the script drops everything in the current directory

while its running, check `ls -l /proc/<pid>/cwd` on the pid of the currently running cardano-node
is the working directory what you expected?

**Comment by hiramf** [comment]
@cleverca22 That worked, thank you. 

Final service file looks like this: 
```
After=network.target

[Service]
WorkingDirectory=/home/johndoe/cardano-sl/
ExecStart=/home/johndoe/cardano-sl/connect-testnet-wallet
Restart=always

[Install]
WantedBy=multi-user.target
```
