### ISSUE TITLE
how to read and run the Cardano code?

### ISSUE THREAD

**Issue by yeeacksonideo** [input-output-hk/cardano-sl#4150]
I want to study the Ouroboros PoS protocol and modify it, but I don't know how to start with the source code.who can help me !!!

**Comment by yeeacksonideo** [comment]
@iohk-devops @erikd

**Comment by erikd** [comment]
The code is the last place to look to understand how Ourorboros works. I would suggest reading any papers found [here](https://iohk.io/research/papers/) with "Ouroboros" in the title.

Also the source code in this repository is the old code base which will be discarded as soon as the new code base (publically avaliable elsewhere under https://github.com/input-output-hk) is ready.
