### ISSUE TITLE
stack build failed cause by stylinsh-haskell

### ISSUE THREAD

**Issue by niceworld1206** [input-output-hk/cardano-sl#4165]
i see build depend on stylish-haskell

- location:
    git: https://github.com/input-output-hk/stylish-haskell.git
    commit: ecfd3b307d8d13a6d12aff03055f25a39a17e182
  extra-dep: true

but this commit id seems not exist .  i start to get this error from 13th jun,  it works fine before.

here is the error: 

Please ensure that commit ecfd3b307d8d13a6d12aff03055f25a39a17e182 exists within https://github.com/input-output-hk/stylish-haskell.git
Received ExitFailure 128 when running
Raw command: /usr/bin/git --git-dir=.git reset --hard ecfd3b307d8d13a6d12aff03055f25a39a17e182 --
Run from: /root/cardano-sl/.stack-work/downloaded/UHugMzdVdOSU/
Standard error:

fatal: Could not parse object 'ecfd3b307d8d13a6d12aff03055f25a39a17e182'

**Comment by erikd** [comment]
If all you want to do is build `cardano-sl`, removing `stylish-haskell` from the `stack.yaml` file safe.
