### ISSUE TITLE
s2i Failed stack build cardano sl

### ISSUE THREAD

**Issue by sputniiik** [input-output-hk/cardano-sl#4178]
```
Building cardano-sl-networking

stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=1 --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-networking

Could not parse '/opt/app-root/src/stack.yaml':
Aeson exception:
Error in $.packages[32]: failed to parse field 'packages': expected Text, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
Build failed

```
I am trying to compile cardano-sl with stack: I
I've installed all the pre-requierements and I installed the last Stack version at the moment.
Current Stack version: 2.1.1

**Comment by erikd** [comment]
The file `/opt/app-root/src/stack.yaml` is not part of the `cardano-sl` repo.

**Comment by sputniiik** [comment]
yes that's right I am ussing s2i to build it

**Comment by erikd** [comment]
What is `s2i` ?

**Comment by sputniiik** [comment]
https://github.com/openshift/source-to-image

> Source-to-Image (S2I) is a toolkit and workflow for building reproducible container images from source code. S2I produces ready-to-run images by injecting source code into a container image and letting the container prepare that source code for execution

I have installed all the dependencies to be able to build it with stack, so I am not sure which could be the best approach.

**Comment by erikd** [comment]
The current problem is the file `/opt/app-root/src/stack.yaml` which I suspect is part of `s2i`. Its definitely not a problem I can help you with.

**Comment by sputniiik** [comment]
this /opt/app-root/src/stack.yaml is the same than  cardano-sl/stack.yaml
::::: 
 resolver: lts-12.17

flags:
ether:
disable-tup-instances: true

extra-package-dbs: []
......................... etc 

maybe is something similar to this one: https://github.com/haskell/haskell-ide-engine/issues/796

**Comment by sputniiik** [comment]
@erikd  is true that this repository is deprecated?

**Comment by erikd** [comment]
This code base is the one that is currently running the Cardano chain.

However, this code base is in maintenance mode while work on a completely new code base is underway.
