### ISSUE TITLE
cardano-sl cant  sync

### ISSUE THREAD

**Issue by Alteryy** [input-output-hk/cardano-sl#4228]
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:21.49 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:26.50 UTC] ticking the slot in the submission layer...
[cardano-sl.*production*:Info:ThreadId 329] [2019-08-20 04:55:28.47 UTC] Triggering recovery because we need it
[cardano-sl.*production*:Debug:ThreadId 329] [2019-08-20 04:55:28.47 UTC] Recovery triggered, requesting tips from neighbors
[cardano-sl.diffusion.outboundqueue.self:Debug:ThreadId 329] [2019-08-20 04:55:28.47 UTC] message MsgRequestBlockHeaders Nothing not enqueued to any nodes of type NodeRelay since no such (relevant) peers listed in Peers {peersRoutes = Routes {_routesCore = [], _routesRelay = [], _routesEdge = []}, peersClassification = fromList []}
[cardano-sl.*production*:Debug:ThreadId 329] [2019-08-20 04:55:28.47 UTC] Finished requesting tips for recovery
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:31.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:36.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:41.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:46.50 UTC] ticking the slot in the submission layer...
[cardano-sl.*production*:Info:ThreadId 329] [2019-08-20 04:55:49.47 UTC] Triggering recovery because we need it
[cardano-sl.*production*:Debug:ThreadId 329] [2019-08-20 04:55:49.47 UTC] Recovery triggered, requesting tips from neighbors
[cardano-sl.diffusion.outboundqueue.self:Debug:ThreadId 329] [2019-08-20 04:55:49.47 UTC] message MsgRequestBlockHeaders Nothing not enqueued to any nodes of type NodeRelay since no such (relevant) peers listed in Peers {peersRoutes = Routes {_routesCore = [], _routesRelay = [], _routesEdge = []}, peersClassification = fromList []}
[cardano-sl.*production*:Debug:ThreadId 329] [2019-08-20 04:55:49.47 UTC] Finished requesting tips for recovery
[cardano-sl.*production*:Info:ThreadId 334] [2019-08-20 04:55:51.45 UTC] createAndArchiveCheckpoints is starting...
[cardano-sl.*production*:Info:ThreadId 334] [2019-08-20 04:55:51.45 UTC] pruneAndCompress pruned 0 old archives.
[cardano-sl.*production*:Info:ThreadId 334] [2019-08-20 04:55:51.45 UTC] pruneAndCompress compressed 1 archives.
[cardano-sl.diffusion:Error:ThreadId 318] [2019-08-20 04:55:51.47 UTC] DNS resolution for [NodeAddrDNS "todo.defaultDnsDomain.com" Nothing] gave no results
[cardano-sl.diffusion:Error:ThreadId 318] [2019-08-20 04:55:51.47 UTC] DNS resolution failure for [NodeAddrDNS "todo.defaultDnsDomain.com" Nothing]: [NameError]
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:51.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:55:56.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:56:01.50 UTC] ticking the slot in the submission layer...
[cardano-sl.node:Debug:ThreadId 336] [2019-08-20 04:56:06.50 UTC] ticking the slot in the submission layer...
---node-info---
curl http://localhost:8090/api/v1/node-info
{"data":{"syncProgress":{"quantity":0,"unit":"percent"},"blockchainHeight":null,"localBlockchainHeight":{"quantity":0,"unit":"blocks"},"localTimeInformation":{"status":"available","localTimeDifference":{"quantity":4570,"unit":"microseconds"}},"subscriptionStatus":{}},"status":"success","meta":{"pagination":{"totalPages":1,"page":1,"perPage":1,"totalEntries":1}}}
---node-info---
plz,help.

**Comment by penuel-li** [comment]
@Alteryy How did you solve it?
