### ISSUE TITLE
Build from source using nix-build broken since 3.0.3

### ISSUE THREAD

**Issue by hugorut** [input-output-hk/cardano-sl#4236]
Instructions on how to build cardano-sl as specified [here](https://github.com/input-output-hk/cardano-sl/blob/master/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) state that a nix installation is the preferred method of building cardano from source.

The docs state to run the following command after cloning master

```
$ nix-build -A cardano-sl-node-static --out-link master
```

However since release `3.0.3` this fails with output:

```
error: attribute 'cardano-sl-static' in selection path 'cardano-sl-static' not found
```

The last working release using the nix-build method is `3.0.2`. Is there any updated documentation on how to build latest releases. Would this be `stack` preferred?

**Comment by disassembler** [comment]
No, we switched to haskell.nix and the doc wasn't updated. nix-build -A connecScripts.mainnet.wallet is probably what you want as that builds a shell script that provides all the command arguments and files needed to run it as well. If you do just want to build the raw exes for the different pieces you could checkout `nix repl nix-tools.exes` and poke around the different exes provided. All exes are static now by default.

Note that no further development is being done in this repository and the new node is being developed in cardano-node repository.

**Comment by hugorut** [comment]
Thanks for the response, much appreciated
