### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by alexqrid** [input-output-hk/cardano-sl#4249]
Is your [installation guide](https://github.com/input-output-hk/cardano-sl/blob/develop/docs/how-to/build-cardano-sl-and-daedalus-from-source-code.md) out of date ?
I tried to run my own node using that guide, but the installation via nix fails, so do installation via stack.
Nix error:
```
$ nix-build -A cardano-sl-node-static --out-link master
error: attribute 'cardano-sl-node-static' in selection path 'cardano-sl-node-static' not found
```
Stack error:
```
$ ./scripts/build/cardano-sl.sh
Going to build:  cardano-sl-networking cardano-sl-binary cardano-sl-util cardano-sl-crypto cardano-sl-core cardano-sl-db cardano-sl-chain cardano-sl-infra cardano-sl cardano-sl-node cardano-sl-client cardano-sl-generator cardano-sl-auxx cardano-sl-tools cardano-sl-explorer cardano-sl-wallet
Building cardano-sl-networking

stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=1 --no-run-tests --no-run-benchmarks --dependencies-only  cardano-sl-networking

Could not parse '/home/cardano/cardano-sl/stack.yaml':
Aeson exception:
Error in $.packages[33]: failed to parse field 'packages': expected Text, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```
Where can I find the correct installation guide?

**Comment by kss-espeo** [comment]
I'm having the same issue on `Ubuntu 18.10` . I tried to apply some fix suggestions from relevant tickets (such as #2212) but with no luck. Can we get some assistance with that, please?

**Comment by oldcryptogeek** [comment]
Duplicated @ #4234

**Comment by IaeShubNiggurath** [comment]
yeah same on Debian: 
nix-build -> error: attribute 'cardano-sl-static.... in selection path ... not found

nix-shell -> error

stack way -> error
