### ISSUE TITLE
Several new "panicked at" errors while bootstrap

### ISSUE THREAD

**Issue by Sailoshi** [input-output-hk/cardano-sl#4272]
Jan 30 12:22:58 srv10920 node-start.sh[12008]: thread 'main' panicked at 'internal error: entered unreachable code', /cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.22/src/runtime/threadpool/mod.rs:296:26

std::panicking::begin_panic::h77d90ac0da8eb2f0
  12:     0x560a289c7f43 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h6fa3cf1bc1d4ccac
  13:     0x560a2895659a - futures::task_impl::Spawn<T>::poll_future_notify::h10839e9a53cd1b34
  14:     0x560a28d96cae - std::thread::local::LocalKey<T>::with::hbd30399723fcbd10
  15:     0x560a29055333 - jormungandr::main::hd76f89f91fbc246e
  16:     0x560a290d6033 - std::rt::lang_start::{{closure}}::heda679cf5cab78bf
  17:     0x560a29048c98 - main
  18:     0x7f03dfe34b97 - __libc_start_main
  19:     0x560a2890c994 - <unknown>
  20:                0x0 - <unknown>

Can not bootstrap on jor 0.8.8 with IOHK peers.

**Comment by erikd** [comment]
This repo is for the old Haskell codebase and the error here is for jormungandr which is written in Rust. The repo is here https://github.com/input-output-hk/jormungandr
