### ISSUE TITLE
 Failed to verify blocks: stake distribution for epoch #179 is unknown

### ISSUE THREAD

**Issue by shuhuan2014** [input-output-hk/cardano-sl#4277]
Can not synchronize the epoch ##179 ,

anyone knows how to solve this problem ?

```
[cardano-sl.*production*:Warning:ThreadId 353] [2020-03-12 03:32:56.35 UTC] handleRecoveryE: error handling nodeId="13.228.101.136:3000:0", header=39a8065bdcfbe6dd: BlockNetLogicException: DialogUnexpected "s**_take distribution for epoch #179 is unknown_**"
[cardano-sl.*production*:Warning:ThreadId 353] [2020-03-12 03:32:56.35 UTC] Recovery mode communication dropped with peer "13.228.101.136:3000:0"
[cardano-sl.*production*:Debug:ThreadId 353] [2020-03-12 03:32:56.35 UTC] Attempting to restart recovery
[cardano-sl.*production*:Debug:ThreadId 353] [2020-03-12 03:32:58.35 UTC] Recovery triggered, requesting tips from neighbors
[cardano-sl.diffusion.outboundqueue.self:Debug:ThreadId 353] [2020-03-12 03:32:58.35 UTC] inFlight = fromList []
[cardano-sl.diffusion.outboundqueue.self:Debug:ThreadId 353] [2020-03-12 03:32:58.35 UTC] Rejected alternative NodeId 13.228.101.136:3000:0 as it has a recent failure
[cardano-sl.diffusion.outboundqueue.self:Warning:ThreadId 353] [2020-03-12 03:32:58.35 UTC] could not choose suitable alternative from [NodeId 13.228.101.136:3000:0]
[cardano-sl.diffusion.outboundqueue.self:Error:ThreadId 353] [2020-03-12 03:32:58.35 UTC] enqueue instruction EnqueueAll NodeRelay (MaxAhead 1) PHigh failed to enqueue message MsgRequestBlockHeaders Nothing to forwarding sets [[NodeId 13.228.101.136:3000:0]]
[cardano-sl.*production*:Debug:ThreadId 353] [2020-03-12 03:32:58.35 UTC] Finished requesting tips for recovery
```

**Comment by erikd** [comment]
What version is this? Is it a release version or something compiled from Git? If the latter, please supply the git hash.

**Comment by shuhuan2014** [comment]
> What version is this? Is it a release version or something compiled from Git? If the latter, please supply the git hash.

commit 1a792d7cd0f0c93a0f0c28f66372bce3c3808dbd (HEAD -> master, tag: 3.1.0, origin/master)
Merge: 6e413d2d4 263b8cdc5
Author: iohk-bors[bot] <43231472+iohk-bors[bot]@users.noreply.github.com>
Date:   Tue Sep 24 13:39:43 2019 +0000

**Comment by shuhuan2014** [comment]
commit 1a792d7cd0f0c93a0f0c28f66372bce3c3808dbd (HEAD -> master, tag: 3.1.0, origin/master)

**Comment by shuhuan2014** [comment]
[cardano-sl.diffusion.outboundqueue.self:Warning:ThreadId 2120] [2020-03-12 04:00:56.44 UTC] sending MsgRequestBlocks (fromList [NodeId 13.228.101.136:3000:0]) to NodeId 13.228.101.136:3000:0 failed with BlockNetLogicException: DialogUnexpected "stake distribution for epoch #179 is unknown" :: SomeException
[cardano-sl.*production*:Warning:ThreadId 353] [2020-03-12 04:00:56.44 UTC] handleRecoveryE: error handling nodeId="13.228.101.136:3000:0", header=296359d690c79707: BlockNetLogicException: DialogUnexpected "stake distribution for epoch #179 is unknown"
[cardano-sl.*production*:Warning:ThreadId 353] [2020-03-12 04:00:56.44 UTC] Recovery mode communication dropped with peer "13.228.101.136:3000:0"
[cardano-sl.*production*:Debug:ThreadId 353] [2020-03-12 04:00:56.44 UTC] Attempting to restart recovery

**Comment by shuhuan2014** [comment]
[cardano-sl.*production*:Debug:ThreadId 2854] [2020-03-12 04:14:16.86 UTC] Rolling: verifying
[cardano-sl.*production*:Info:ThreadId 2854] [2020-03-12 04:14:16.86 UTC] slogVerifyBlocks: Consensus era is OBFT ObftLenient
[cardano-sl.diffusion:Debug:ThreadId 2853] [2020-03-12 04:14:17.05 UTC] Updating Window: 1024 to 2048
[cardano-sl.diffusion:Debug:ThreadId 2853] [2020-03-12 04:14:17.17 UTC] Updating Window: 1024 to 2048
[cardano-sl.*production*:Debug:ThreadId 2854] [2020-03-12 04:14:17.96 UTC] usVerifyBlocks OBFT: We're on epoch boundary. Running processGenesisBlock
[cardano-sl.*production*:Debug:ThreadId 2854] [2020-03-12 04:14:17.96 UTC] Rolling: run applyAMAP: apply as much as possible after `verifyBlocksPrefix` failure: ApplyBlocksVerifyFailure (VerifyBlocksError "stake distribution for epoch #179 is unknown")

**Comment by erikd** [comment]
I would suggest trying tag https://github.com/input-output-hk/cardano-sl/releases/tag/3.2.0 .

**Comment by shuhuan2014** [comment]
> I would suggest trying tag https://github.com/input-output-hk/cardano-sl/releases/tag/3.2.0 .

should i rebuild again ?

**Comment by erikd** [comment]
You can only try that tag by rebuilding.

**Comment by shuhuan2014** [comment]
> You can only try that tag by rebuilding.

I have many wallets created in the old version.

how to transfer to new version?

**Comment by erikd** [comment]
No need to transfer. Tag 3.2.0 or `cardano-sl` is compatible with tag 3.1.0.

**Comment by shuhuan2014** [comment]
> No need to transfer. Tag 3.2.0 or `cardano-sl` is compatible with tag 3.1.0.

Do i need to delete the old folder: state-wallet-mainnet ?

**Comment by erikd** [comment]
Have you tried deleting that folder and re-running with tag 3.1.0? If you haven't that would be worth trying first.

**Comment by shuhuan2014** [comment]
> Have you tried deleting that folder and re-running with tag 3.1.0? If you haven't that would be worth trying first.

OK, i will try to change the folder name to make backup

**Comment by shuhuan2014** [comment]
Now start to scratch.

BUT the problem is the API can not get data of my ADA wallet.
should i wait ?

curl -X GET https://127.0.0.1:8090/api/v1/wallets \
>   -H "Accept: application/json; charset=utf-8" \
>   -H "Content-Type: application/json; charset=utf-8" \
>   --cacert /root/cardano/cardano-sl/state-wallet-mainnet/tls/client/ca.crt \
>   --cert /root/cardano/cardano-sl/state-wallet-mainnet/tls/client/client.pem \


{"data":[],"status":"success","meta":{"pagination":{"totalPages":1,"page":1,"perPage":10,"totalEntries":0}}}
-----------------------------
[cardano-sl.*production*:Info:377] [2020-03-12 04:45:18.96 UTC] Trying to apply blocks w/o rollback. First 3: [MainBlockHeader:
    hash: 91237e7e86349961cb23f5f1486231fa1ea127ed6531f20717443d73a6a93bca
    previous block: 3616fdace43c820151fb83c7919f792ccb10cf8c801c11dfa1c0129ee139e6b9
    slot: 4224th slot of 0th epoch
    difficulty: 4225
    leader: pub:993a8f05
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:993a8f05, dPk = pub:89c29f8c } }
    block: v0.0.0
    software: cardano-sl:0

**Comment by erikd** [comment]
You have just deleted the state directory. You have to wait for the node to sync.

**Comment by shuhuan2014** [comment]
> You have just deleted the state wallet. You have to wait for the node to sync.

the sync process stoped automatically.

anything wrong ?

```
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] Rolling: verifying
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] verifyBlocksPrefix: 64
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:47.94 UTC] slogVerifyBlocks: Consensus era is Original
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.98 UTC] Rolling: Verification done, applying unsafe block
[cardano-sl.node:Debug:316] [2020-03-12 04:53:47.99 UTC] applying some blocks (non-rollback)
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:48.00 UTC] Verifying and applying blocks done
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:48.00 UTC] MemPool metrics release: ApplyBlock modify time was 62231mcs size is 0
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:48.00 UTC] Not relaying block in recovery mode
```

**Comment by shuhuan2014** [comment]
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] MemPool metrics release: ApplyBlock modify time was 63302mcs size is 0
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] Not relaying block in recovery mode
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:47.94 UTC] Blocks have been adopted: [e0519792aa866731, 9ebb51a058766e74, 1167053451705108, 42d58cdb8847511f, 7413495aa008767d, 28e6be254a20cc93, 7befdbb56b98a7d9, a6d78d6514d74f15, 2c85004d0964d889, 74f98c8a258de426, e745055be8e2cb52, 370128cc7f920ae6, f3377ea7338949e1, ea89ad167677d7d4, 17855de2f101b41f, a66b4ba0af6c6bd0, 958bf972a92d6e6d, 13edfb5de5ed26dc, 743fd656d6d8224f, a86227add316a2d8, 0edb672face4d6b2, c2622d94c8e8980d, d0754ec12b4d29a4, a0ee37b3e175a58e, 66ac5919f73f846f, db8abe3defc40a94, bb82e8344804c5ee, edf428a556c0fd7c, e72b98f782ed147e, f408a2f2271d7209, 9373f62cbd53585e, d320c9262cbcd7d9, 0e4d0313a3335ee3, f41947c62703aaa3, ea5bd4ef4a87beda, b121fdb47a0a81c6, 6a27adb118f1126d, 26611fde1308161f, 89765f6cc1d58dcd, 0db8cdd043d4fcb9, dd39df79c096694a, d614fc4726b0629d, 7c86a5a226f4e891, 0075864fb775a3b9, 4a176cc46f6f802a, 065a2c3e156815e6, 936abd0ded16db58, ecfc8b7f4705ae08, 7dc5f85e266c4983, 49962c744f230ed2, 3926ec88fc815048, c573a2db9e13baec, 2d61f7aaec0d28c8, d283274f5a060e1b, 2cbf42f537ccb8f7, 66bffed068c48880, 8ffefd034890eb0e, 520d0b11c0b4ab55, 116db5fcdb2eb6eb, 78c0eb6c6b980eca, fd4e16746c8bfea2, fb4f353f2cfb205f, 45252ba4ca3d11c6, 194644f84b936ac0]
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] handleBlocks: processing
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] Handling block w/ LCA, which is 194644f8
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:47.94 UTC] Trying to apply blocks w/o rollback. First 3: [MainBlockHeader:
    hash: 86275217c26001b3cbd939d1142554ed5ae7f8e67cd9e9db299e435faded4a7f
    previous block: 194644f84b936ac04d14db8a674f221416c863ea4c9472a33a3f3449fe9e1a52
    slot: 14172nd slot of 12th epoch
    difficulty: 273333
    leader: pub:1bc97a2f
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:1bc97a2f, dPk = pub:61261a95 } }
    block: v0.0.0
    software: cardano-sl:2
, MainBlockHeader:
    hash: 26cd024b35567768d32e677666dc0557a42a22caa87f7fa12505803c611c8035
    previous block: 86275217c26001b3cbd939d1142554ed5ae7f8e67cd9e9db299e435faded4a7f
    slot: 14173rd slot of 12th epoch
    difficulty: 273334
    leader: pub:26566e86
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:26566e86, dPk = pub:f14f712d } }
    block: v0.0.0
    software: cardano-sl:2
, MainBlockHeader:
    hash: aa2af9ee04fd1aadd230885b53e9ba0620819f06f912e8471bd3dd924d9b3de9
    previous block: 26cd024b35567768d32e677666dc0557a42a22caa87f7fa12505803c611c8035
    slot: 14174th slot of 12th epoch
    difficulty: 273335
    leader: pub:50733161
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:50733161, dPk = pub:e8c03a03 } }
    block: v0.0.0
    software: cardano-sl:2
]
Last 3: [MainBlockHeader:
    hash: d5b8e4bf17b654744fc770a0efaf05bd71dbc1f19e61a9182b41f847f9d50ec0
    previous block: cb60dcd5fc2bfb9b64535768962aed9c95c2c6391df97085be8655710d13b823
    slot: 14233rd slot of 12th epoch
    difficulty: 273394
    leader: pub:9a6fa343
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:9a6fa343, dPk = pub:8b532076 } }
    block: v0.0.0
    software: cardano-sl:2
, MainBlockHeader:
    hash: bee89306092b7e83818df4f43772d990343a7c6105ab703165d6e61932e4f390
    previous block: d5b8e4bf17b654744fc770a0efaf05bd71dbc1f19e61a9182b41f847f9d50ec0
    slot: 14234th slot of 12th epoch
    difficulty: 273395
    leader: pub:1bc97a2f
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:1bc97a2f, dPk = pub:61261a95 } }
    block: v0.0.0
    software: cardano-sl:2
, MainBlockHeader:
    hash: 8578e4790e0758a16665837a2a41b932c57821eeeebb04a82dab7f7edf482f82
    previous block: bee89306092b7e83818df4f43772d990343a7c6105ab703165d6e61932e4f390
    slot: 14235th slot of 12th epoch
    difficulty: 273396
    leader: pub:50733161
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:50733161, dPk = pub:e8c03a03 } }
    block: v0.0.0
    software: cardano-sl:2
]
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] MemPool metrics wait: ApplyBlock queue length is 1
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] MemPool metrics acquire: ApplyBlock wait time was 12mcs
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:47.94 UTC] Verifying and applying blocks...
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] Rolling: verifying
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.94 UTC] verifyBlocksPrefix: 64
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:47.94 UTC] slogVerifyBlocks: Consensus era is Original
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:47.98 UTC] Rolling: Verification done, applying unsafe block
[cardano-sl.node:Debug:316] [2020-03-12 04:53:47.99 UTC] applying some blocks (non-rollback)
[cardano-sl.*production*:Info:383] [2020-03-12 04:53:48.00 UTC] Verifying and applying blocks done
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:48.00 UTC] MemPool metrics release: ApplyBlock modify time was 62231mcs size is 0
[cardano-sl.*production*:Debug:383] [2020-03-12 04:53:48.00 UTC] Not relaying block in recovery mode

**Comment by erikd** [comment]
How do you know it stopped?

**Comment by shuhuan2014** [comment]
the process of cardano-node is dead. and the port 8090 can not access

**Comment by erikd** [comment]
If it died where is the error message?

**Comment by shuhuan2014** [comment]
this is the last log message

```
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.45 UTC] Rolling: Verification done, applying unsafe block
[cardano-sl.node:Debug:316] [2020-03-12 05:22:34.46 UTC] applying some blocks (non-rollback)
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.48 UTC] Verifying and applying blocks done
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] MemPool metrics release: ApplyBlock modify time was 84697mcs size is 0
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] Not relaying block in recovery mode
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.48 UTC] Blocks have been adopted: [38b0c38769dd2b1e, be3a2725f4695fca, d31d7d44634d64ff, b36ec10eb10d63d7, 4d2303739126f84a, 6baa4ce3b11c1a7f, e8358531e2e28e07, eafb3f7257ee38f1, 6dc3ded31a123b67, fa44be6e1f88ecd7, e4f51a40d1b54b31, 354f2dac9e4dec3b, 3ac3928af88b54a8, 3c6fb54a8fd67033, 61127b944bee18f5, 8368cf64d627a08f, 1d291ce452cdc5d9, ae973bd56614bdce, 08beb19507a57b18, 75b557e264306925, 369104b94f8016e0, 5fb5d4b7f88362b0, 3bcfe877818acf94, ddb142c400416b4c, e74fe942c2c17f69, 9cae637d36a87351, 13c309cdf0477b3a, 60bdcbf68417948f, 52ec5b5c11b536c5, 7e399636b729d7e8, 30f39dfffb1f399b, 2ec76ae576112c7b, 957e3b1927a8f2aa, ecb55f8ee182e2ae, 322ea62c51189cfa, 0f5b72e01c036dd9, 0bad7da8416b3245, 6fc4c39cd9034784, 8a7341fc92d67944, 92e142bf4b897f59, fd1bdc49906a8659, 4f60d3dc26498f8b, 015f742cb8918759, e951c51561f001a9, 8712f6ea5246dfac, 6c919971853f4f1b, f804bc918dba0606, fc8260a9b2ccda2b, ff572f771ea84942, 3456a3455f384d1c, ca285d3eede34c99, 120915041dcc809b, 32d1a74e5173e837, 01b4177c4a36c504, eb383dbb43fd8753, e8a3c05b4798c440, 0ecffde407d01861, 2ec27053968127e6, 750bb1f525703a20, 1e1129ee1061401b, c088e3c8c61fc3d8, 65f7c64e1271d2c1, 8ff2b571d097a51d, dbe5a93c669a174d]
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] handleBlocks: processing
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] Handling block w/ LCA, which is dbe5a93c
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.48 UTC] Trying to apply blocks w/o rollback. First 3: [MainBlockHeader:
    hash: 0a9d610dcfd81aa6c5728ed08ca7e6d80c8f4a579a42cc9642b118d10254fa3e
    previous block: dbe5a93c669a174d6fc92ce6d84212d313f7649df7f3fa6ae0d758d069737a2d
    slot: 15269th slot of 20th epoch
    difficulty: 447213
    leader: pub:9a6fa343
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:9a6fa343, dPk = pub:8b532076 } }
    block: v0.1.0
    software: cardano-sl:0
, MainBlockHeader:
    hash: 9d49740a184042b0014d41234da53520d2a9785e1153fc7b0b9f6a2dd9c68201
    previous block: 0a9d610dcfd81aa6c5728ed08ca7e6d80c8f4a579a42cc9642b118d10254fa3e
    slot: 15270th slot of 20th epoch
    difficulty: 447214
    leader: pub:50733161
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:50733161, dPk = pub:e8c03a03 } }
    block: v0.1.0
    software: cardano-sl:0
, MainBlockHeader:
    hash: c0a8f12a7062aee7daca2be1570bdb7626f646266960d8ef0e9f298c80f0fd3b
    previous block: 9d49740a184042b0014d41234da53520d2a9785e1153fc7b0b9f6a2dd9c68201
    slot: 15271st slot of 20th epoch
    difficulty: 447215
    leader: pub:d2965c86
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:d2965c86, dPk = pub:9180d818 } }
    block: v0.1.0
    software: cardano-sl:0
]
Last 3: [MainBlockHeader:
    hash: 78146314179c040493cc285216487cfc9f31cac71221a98293547e924a540e1f
    previous block: f769f3a8e5d7482c271bcb06cecd208b23d954a5b74a2b0f99b2d94066164ae1
    slot: 15330th slot of 20th epoch
    difficulty: 447274
    leader: pub:d2965c86
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:d2965c86, dPk = pub:9180d818 } }
    block: v0.1.0
    software: cardano-sl:0
, MainBlockHeader:
    hash: 2226aafb6f4713e8580207b32179dd2ccb616575577925bc542c02ad10efd595
    previous block: 78146314179c040493cc285216487cfc9f31cac71221a98293547e924a540e1f
    slot: 15331st slot of 20th epoch
    difficulty: 447275
    leader: pub:1bc97a2f
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:1bc97a2f, dPk = pub:61261a95 } }
    block: v0.1.0
    software: cardano-sl:0
, MainBlockHeader:
    hash: efcb0e8d4f373aceab733b1a57b8e163a469a922996c45f62fd9126e7151e85b
    previous block: 2226aafb6f4713e8580207b32179dd2ccb616575577925bc542c02ad10efd595
    slot: 15332nd slot of 20th epoch
    difficulty: 447276
    leader: pub:26566e86
    signature: BlockPSignatureHeavy: Proxy signature { psk = ProxySk { w = #0, iPk = pub:26566e86, dPk = pub:f14f712d } }
    block: v0.1.0
    software: cardano-sl:0
]
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] MemPool metrics wait: ApplyBlock queue length is 1
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] MemPool metrics acquire: ApplyBlock wait time was 10mcs
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.48 UTC] Verifying and applying blocks...
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] Rolling: verifying
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.48 UTC] verifyBlocksPrefix: 64
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.48 UTC] slogVerifyBlocks: Consensus era is Original
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.54 UTC] Rolling: Verification done, applying unsafe block
[cardano-sl.node:Debug:316] [2020-03-12 05:22:34.55 UTC] applying some blocks (non-rollback)
[cardano-sl.*production*:Info:378] [2020-03-12 05:22:34.57 UTC] Verifying and applying blocks done
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.57 UTC] MemPool metrics release: ApplyBlock modify time was 86828mcs size is 0
[cardano-sl.*production*:Debug:378] [2020-03-12 05:22:34.57 UTC] Not relaying block in recovery mode
```

**Comment by erikd** [comment]
There is nothing in that log indicating that the program terminated.

**Comment by shuhuan2014** [comment]
the PID of cardano-node is dead. and the port 8090 can not access

**Comment by shuhuan2014** [comment]
and no log generate again, stop there

**Comment by erikd** [comment]
What about the kernel log? Anything there?

**Comment by erikd** [comment]
The kernel logs might indicate two things:

* the process being killed by the OOM killer (so add memory)
* the process segfaulting (which is probably also a consequence of insufficient memory)

**Comment by shuhuan2014** [comment]
> The kernel logs might indicate two things:
> 
> * the process being killed by the OOM killer (so add memory)
> * the process segfaulting (which is probably also a consequence of insufficient memory)

Thank you, i will change to another Linux server to try

**Comment by erikd** [comment]
Did you see either of these things in the linux kernel log? If you have not seen either of those two kernel messages, that may not be the problem.

**Comment by erikd** [comment]
Any update on this?

**Comment by erikd** [comment]
Closing this.
