### ISSUE TITLE
[CSL-294] Refactor wallet daedalus storage

### ISSUE THREAD

**Issue by jagajaga** [input-output-hk/cardano-sl#665]
<blockquote>@flyingleafe</blockquote>

Need to reach consensus with @akegalj about how daedalus data will be injected into wallet code.

**Comment by akegalj** [comment]
@jagajaga 
> Need to reach consensus with @akegalj about how daedalus data will be injected into wallet code.
not pretty clear what is this about. I guess if its closed, everything should be ok.
