### ISSUE TITLE
[CSL-324] Kademlia memory consumption expertise

### ISSUE THREAD

**Issue by jagajaga** [input-output-hk/cardano-sl#695]
<blockquote>@shersh</blockquote>

Origin of this issue is here: https://github.com/serokell/kademlia/commit/bf328a1315a436c58961d4315bb2ad835b45d1d4#commitcomment-20221091

Basically we need to investigate Kademlia on possible memory issues, how much memory it consumes, should line of code under comment message be more smart.

**Comment by jagajaga** [comment]
<blockquote>@georgeee</blockquote>

It should be investigated, how Kademlia handles lot of nodes appearing and disappearing over time.
E.g. are internal structures (pending/polled) properly cleaned

Another concern is how node behaves when load on it increases.

In general I think it's possible to implement Kademlia with O(n) memory where n is number of nodes in buckets. Output from this issue:
1. Reasoning why it should be O(n)
2. Corresponding commitments to make 1. true

Or reasoning why 1. is impossible and which way we went to make thing not that bad.

**Comment by jagajaga** [comment]
<blockquote>@georgeee</blockquote>

Well... I thought and understood O(n) is impossible in general, cause arbitrary number of nodes may query us for `find_node` and each such request requires some state to be handled.
For this case I propose to introduce some limit on incoming requests. If actual number of request exceeds, we fall back to simplified strategy, replying to `find_node` using only data from buckets (and this probably should be marked in outgoing message, like boolean flag that node is loaded and can't handle general query).

**Comment by shersh** [comment]
@jagajaga  I think you did mean @ChShersh not me =)

**Comment by ChShersh** [comment]
@shersh Do you know Haskell? Wanna work with us to avoid this confusion eventually? :)

**Comment by shersh** [comment]
@ChShersh Nope) I have 10 years expierence with C#.
And experiments with Elixir )
