### ISSUE TITLE
[CSL-463] Error processing and reporting

### ISSUE THREAD

**Issue by jagajaga** [input-output-hk/cardano-sl#832]
<blockquote>@flyingleafe</blockquote>

We need come up with semantically correct HTTP error codes and messages for these types of errors:

*General*:
* parse errors (e.g. address parsing) - definitely shouldn't be 404
* more informative messages for 404 errors (address/transaction not found)
 
*Sending*
* "Not enough money" error
 
*Update operations*
* 404 errors on attempt to update non-existing entity

That's it, maybe missed something.

**Comment by jagajaga** [comment]
<blockquote>@akegalj</blockquote>

This is probably duplicate of https://issues.serokell.io/issue/DAE-5 . I would rather continue this discussion in DAE thread, because that thread is mostly with considered with wallet (Web).

I mentioned there quick solution for this, and that would be parsing body of error messages and rethrowing error with body content. I think this would be sufficient for now. That way frontend will have enough info about the error. If we will need more control over errors, like recoveries or similar, then we should manage this with `Either Error a` as said in DAE-5 .

With this simple approach we would just have to rethrow body in purescript side of things and that should add least maintaince cost.

**Comment by jagajaga** [comment]
<blockquote>@flyingleafe</blockquote>

@akegalj https://issues.serokell.io/issue/DAE-5#comment=96-1525

**Comment by akegalj** [comment]
@jagajaga the link is broken
