### ISSUE TITLE
[CSL-478] Introduce some policy regarding fees

### ISSUE THREAD

**Issue by jagajaga** [input-output-hk/cardano-sl#846]
<blockquote>@gromak</blockquote>

1. We need to develop some policy regarding fees. For example: each transaction should have at least `size (tx) / 100` ADA as fees. It's very stupid example, let's invent something more sophisticated.
2. We need to update transaction verification to check fees according to policy developed in (1). I want this logic to be in a separate function. We can start with very stupid policy (e. g. consider all txs valid w. r. t. fees) and after we develop good policy we can change this function accordingly.
3. We need to modify wallet so that it creates txs with enough fees. *It will be separate issue*.

**Comment by CharlesHoskinson** [comment]
See Lars's paper on Tx Fees
[Cardano Transaction Fees (1).pdf](https://github.com/input-output-hk/cardano-sl/files/1037331/Cardano.Transaction.Fees.1.pdf)
