### ISSUE TITLE
[CSL-499] Do FTS and richmen computation in the same iteration

### ISSUE THREAD

**Issue by jagajaga** [input-output-hk/cardano-sl#867]
<blockquote>@gromak</blockquote>

**Comment by omefire** [comment]
I'd like to start my contributions to Cardano by first working on fixing this issue.

**Comment by omefire** [comment]
Can we get more details as to what needs to be done here ?

**Comment by omefire** [comment]
@jagajaga Can we please have an explanation as to why this is being closed ? Is it the case that this issue has already been fixed ?  If so, with what commit ?

**Comment by jagajaga** [comment]
Hello!
First of all thank you for your interest in cardano sl source code.
We are using our own internal issues tracker, so most of the issues were
exported to github by mistake (they were not maintained here, etc.). We are
going to make it public soon so you can check the up-to-date information
there.

**Comment by gromakovsky** [comment]
This particular issue should be postponed, because we have another idea how to implement richmen computation and it's not a priority now.

**Comment by omefire** [comment]
@jagajaga @gromakovsky Thanks for the explanation!
Are there any issues that aren't internal that people like me who aren't part of serokell or IOHK can contribute to ?
